import type { VmbTestDefinitionGroup } from '../../lib.js';

export default [
  [
    'Flow control',
    [
      ['<1>', '<OP_IF <3> OP_ENDIF> OP_EVAL <3> OP_EQUAL', 'Eval-ed OP_IF (3 == 3)', ['chip_eval']],
      ['<1>', 'OP_IF <<3> OP_ENDIF> OP_EVAL <3> OP_EQUAL', 'Eval-ed OP_IF (3 == 3), external OP_IF', ['chip_eval_invalid']],
      ['<0>', '<OP_IF <3> OP_ENDIF> OP_EVAL <3> OP_EQUAL', 'Eval-ed OP_IF (fails on empty stack)', ['chip_eval_invalid']],
      ['<1>', '<OP_IF <3> OP_ELSE <2> OP_ENDIF> OP_EVAL <2> OP_EQUAL', 'Eval-ed OP_IF, OP_ELSE (reject)', ['chip_eval_invalid']],
      ['<0>', '<OP_IF <3> OP_ELSE <2> OP_ENDIF> OP_EVAL <2> OP_EQUAL', 'Eval-ed OP_IF, OP_ELSE (succeed)', ['chip_eval']],
      ['<0>', 'OP_IF <<3> OP_ELSE <2> OP_ENDIF> OP_EVAL <2> OP_EQUAL', 'Eval-ed OP_IF, OP_ELSE (external OP_IF)', ['chip_eval_invalid']],
      ['<0>', '<OP_NOTIF <3> OP_ENDIF> OP_EVAL <3> OP_EQUAL', 'Eval-ed OP_NOTIF (3 == 3)', ['chip_eval']],
      ['<0>', 'OP_NOTIF <<3> OP_ENDIF> OP_EVAL <3> OP_EQUAL', 'Eval-ed OP_NOTIF (3 == 3), external OP_NOTIF', ['chip_eval_invalid']],
      ['<1>', '<OP_NOTIF <3> OP_ENDIF> OP_EVAL <3> OP_EQUAL', 'Eval-ed OP_NOTIF (fails on empty stack)', ['chip_eval_invalid']],
      ['<0>', '<OP_NOTIF <3> OP_ELSE <2> OP_ENDIF> OP_EVAL <2> OP_EQUAL', 'Eval-ed OP_NOTIF, OP_ELSE (reject)', ['chip_eval_invalid']],
      ['<1>', '<OP_NOTIF <3> OP_ELSE <2> OP_ENDIF> OP_EVAL <2> OP_EQUAL', 'Eval-ed OP_NOTIF, OP_ELSE (succeed)', ['chip_eval']],
      ['<1>', 'OP_NOTIF <<3> OP_ELSE <2> OP_ENDIF> OP_EVAL <2> OP_EQUAL', 'Eval-ed OP_NOTIF, OP_ELSE (external OP_NOTIF)', ['chip_eval_invalid']],
      ['<<3>> <OP_EVAL>', 'OP_EVAL <3> OP_EQUAL', 'Eval-ed OP_EVAL (3 == 3)', ['chip_eval']],
      ['<<0>> <OP_EVAL>', 'OP_EVAL <3> OP_EQUAL', 'Eval-ed OP_EVAL (0 == 3)', ['chip_eval_invalid']],
      ['<1> <1>', '<OP_BEGIN OP_UNTIL> OP_EVAL', 'Eval-ed <1> OP_BEGIN OP_UNTIL', ['chip_eval']],
      ['<1> <0>', '<OP_BEGIN OP_UNTIL> OP_EVAL', 'Eval-ed <0> OP_BEGIN OP_UNTIL', ['chip_eval_invalid']],
      ['<1> <1>', 'OP_BEGIN <OP_UNTIL> OP_EVAL', 'Eval-ed <1> OP_BEGIN OP_UNTIL, external OP_BEGIN', ['chip_eval_invalid']],
      ['<1> <OP_BEGIN>', 'OP_EVAL', 'no matching OP_UNTIL', ['chip_eval_invalid']],
      ['<1> <1> <OP_UNTIL>', 'OP_EVAL', 'no matching OP_BEGIN', ['chip_eval_invalid']],
      ['<1> <1> <OP_DROP>', 'OP_EVAL', 'no matching OP_BEGIN (would otherwise succeed)', ['chip_eval']],

      ['<1>', '<OP_IF <3> OP_ENDIF> <0> OP_TUCK OP_DEFINE OP_INVOKE <3> OP_EQUAL', 'Define/invoke-ed OP_IF (3 == 3)', ['chip_functions']],
      ['<1>', 'OP_IF <<3> OP_ENDIF> <0> OP_TUCK OP_DEFINE OP_INVOKE <3> OP_EQUAL', 'Define/invoke-ed OP_IF (3 == 3), external OP_IF', ['chip_functions_invalid']],
      ['<0>', '<OP_IF <3> OP_ENDIF> <0> OP_TUCK OP_DEFINE OP_INVOKE <3> OP_EQUAL', 'Define/invoke-ed OP_IF (fails on empty stack)', ['chip_functions_invalid']],
      ['<1>', '<OP_IF <3> OP_ELSE <2> OP_ENDIF> <0> OP_TUCK OP_DEFINE OP_INVOKE <2> OP_EQUAL', 'Define/invoke-ed OP_IF, OP_ELSE (reject)', ['chip_functions_invalid']],
      ['<0>', '<OP_IF <3> OP_ELSE <2> OP_ENDIF> <0> OP_TUCK OP_DEFINE OP_INVOKE <2> OP_EQUAL', 'Define/invoke-ed OP_IF, OP_ELSE (succeed)', ['chip_functions']],
      ['<0>', 'OP_IF <<3> OP_ELSE <2> OP_ENDIF> <0> OP_TUCK OP_DEFINE OP_INVOKE <2> OP_EQUAL', 'Define/invoke-ed OP_IF, OP_ELSE (external OP_IF)', ['chip_functions_invalid']],
      ['<0>', '<OP_NOTIF <3> OP_ENDIF> <0> OP_TUCK OP_DEFINE OP_INVOKE <3> OP_EQUAL', 'Define/invoke-ed OP_NOTIF (3 == 3)', ['chip_functions']],
      ['<0>', 'OP_NOTIF <<3> OP_ENDIF> <0> OP_TUCK OP_DEFINE OP_INVOKE <3> OP_EQUAL', 'Define/invoke-ed OP_NOTIF (3 == 3), external OP_NOTIF', ['chip_functions_invalid']],
      ['<1>', '<OP_NOTIF <3> OP_ENDIF> <0> OP_TUCK OP_DEFINE OP_INVOKE <3> OP_EQUAL', 'Define/invoke-ed OP_NOTIF (fails on empty stack)', ['chip_functions_invalid']],
      ['<0>', '<OP_NOTIF <3> OP_ELSE <2> OP_ENDIF> <0> OP_TUCK OP_DEFINE OP_INVOKE <2> OP_EQUAL', 'Define/invoke-ed OP_NOTIF, OP_ELSE (reject)', ['chip_functions_invalid']],
      ['<1>', '<OP_NOTIF <3> OP_ELSE <2> OP_ENDIF> <0> OP_TUCK OP_DEFINE OP_INVOKE <2> OP_EQUAL', 'Define/invoke-ed OP_NOTIF, OP_ELSE (succeed)', ['chip_functions']],
      ['<1>', 'OP_NOTIF <<3> OP_ELSE <2> OP_ENDIF> <0> OP_TUCK OP_DEFINE OP_INVOKE <2> OP_EQUAL', 'Define/invoke-ed OP_NOTIF, OP_ELSE (external OP_NOTIF)', ['chip_functions_invalid']],
      ['<<3>> <<0> OP_TUCK OP_DEFINE OP_INVOKE>', '<1> OP_TUCK OP_DEFINE OP_INVOKE <3> OP_EQUAL', 'Define/invoke-ed define/invoke (3 == 3)', ['chip_functions']],
      ['<<0>> <<0> OP_TUCK OP_DEFINE OP_INVOKE>', '<1> OP_TUCK OP_DEFINE OP_INVOKE <3> OP_EQUAL', 'Define/invoke-ed define/invoke (0 == 3)', ['chip_functions_invalid']],
      ['<1> <1>', '<OP_BEGIN OP_UNTIL> <0> OP_TUCK OP_DEFINE OP_INVOKE', 'Define/invoke-ed <1> OP_BEGIN OP_UNTIL', ['chip_functions']],
      ['<1> <0>', '<OP_BEGIN OP_UNTIL> <0> OP_TUCK OP_DEFINE OP_INVOKE', 'Define/invoke-ed <0> OP_BEGIN OP_UNTIL', ['chip_functions_invalid']],
      ['<1> <1>', 'OP_BEGIN <OP_UNTIL> <0> OP_TUCK OP_DEFINE OP_INVOKE', 'Define/invoke-ed <1> OP_BEGIN OP_UNTIL, external OP_BEGIN', ['chip_functions_invalid']],
      ['<1> <OP_BEGIN>', '<0> OP_TUCK OP_DEFINE OP_INVOKE', 'no matching OP_UNTIL', ['chip_functions_invalid']],
      ['<1> <1> <OP_UNTIL>', '<0> OP_TUCK OP_DEFINE OP_INVOKE', 'no matching OP_BEGIN', ['chip_functions_invalid']],
      ['<1> <1> <OP_DROP>', '<0> OP_TUCK OP_DEFINE OP_INVOKE', 'no matching OP_BEGIN (would otherwise succeed)', ['chip_functions']],

      ['<1> <1>', 'OP_IF OP_IF <3> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_IF: Nested OP_IF (3 == 3)', []],
      ['<1> <1>', 'OP_IF OP_IF <0> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_IF: Nested OP_IF (0 == 3)', ['invalid']],
      ['<0> <1>', 'OP_IF OP_NOTIF <3> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_IF: Nested OP_NOTIF (3 == 3)', []],
      ['<0> <1>', 'OP_IF OP_NOTIF <0> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_IF: Nested OP_NOTIF (0 == 3)', ['invalid']],
      ['<1>', 'OP_IF <<3>> OP_EVAL OP_ENDIF <3> OP_EQUAL', 'OP_IF: Nested OP_EVAL (3 == 3)', ['chip_eval']],
      ['<1>', 'OP_IF <<3>> OP_EVAL OP_ENDIF <2> OP_EQUAL', 'OP_IF: Nested OP_EVAL (2 == 3)', ['chip_eval_invalid']],
      ['<1>', 'OP_IF <<3>> <0> OP_TUCK OP_DEFINE OP_INVOKE OP_ENDIF <3> OP_EQUAL', 'OP_IF: Nested define/invoke (3 == 3)', ['chip_functions']],
      ['<1>', 'OP_IF <<3>> <0> OP_TUCK OP_DEFINE OP_INVOKE OP_ENDIF <2> OP_EQUAL', 'OP_IF: Nested define/invoke (2 == 3)', ['chip_functions_invalid']],
      ['<1> <1>', 'OP_IF <1> OP_BEGIN OP_UNTIL OP_ENDIF', 'OP_IF: Nested <1> OP_BEGIN OP_UNTIL', ['chip_loops']],
      ['<1> <1>', 'OP_IF <0> OP_BEGIN OP_UNTIL OP_ENDIF', 'OP_IF: Nested <0> OP_BEGIN OP_UNTIL', ['chip_loops_invalid']],
      ['<1> <1>', 'OP_IF <1> OP_BEGIN OP_ENDIF OP_UNTIL', 'OP_IF: Nested <1> OP_BEGIN OP_UNTIL, external OP_UNTIL', ['chip_loops_invalid']],

      ['<1> <0>', 'OP_IF OP_ELSE OP_IF <3> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_IF, OP_ELSE: Nested OP_IF (3 == 3)', []],
      ['<1> <0>', 'OP_IF OP_ELSE OP_IF <0> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_IF, OP_ELSE: Nested OP_IF (0 == 3)', ['invalid']],
      ['<0> <0>', 'OP_IF OP_ELSE OP_NOTIF <3> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_IF, OP_ELSE: Nested OP_NOTIF (3 == 3)', []],
      ['<0> <0>', 'OP_IF OP_ELSE OP_NOTIF <0> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_IF, OP_ELSE: Nested OP_NOTIF (0 == 3)', ['invalid']],
      ['<0>', 'OP_IF OP_ELSE <<3>> OP_EVAL OP_ENDIF <3> OP_EQUAL', 'OP_IF, OP_ELSE: Nested OP_EVAL (3 == 3)', ['chip_eval']],
      ['<0>', 'OP_IF OP_ELSE OP_ELSE OP_ELSE <<3>> OP_EVAL OP_ENDIF <3> OP_EQUAL', 'OP_IF, OP_ELSE (x3): Nested OP_EVAL (3 == 3)', ['chip_eval']],
      ['<0>', 'OP_IF OP_ELSE <<3>> OP_EVAL OP_ENDIF <2> OP_EQUAL', 'OP_IF, OP_ELSE: Nested OP_EVAL (2 == 3)', ['chip_eval_invalid']],
      ['<0>', 'OP_IF OP_ELSE <<3>> <0> OP_TUCK OP_DEFINE OP_INVOKE OP_ENDIF <3> OP_EQUAL', 'OP_IF, OP_ELSE: Nested define/invoke (3 == 3)', ['chip_functions']],
      ['<0>', 'OP_IF OP_ELSE OP_ELSE OP_ELSE <<3>> <0> OP_TUCK OP_DEFINE OP_INVOKE OP_ENDIF <3> OP_EQUAL', 'OP_IF, OP_ELSE (x3): Nested define/invoke (3 == 3)', ['chip_functions']],
      ['<0>', 'OP_IF OP_ELSE <<3>> <0> OP_TUCK OP_DEFINE OP_INVOKE OP_ENDIF <2> OP_EQUAL', 'OP_IF, OP_ELSE: Nested define/invoke (2 == 3)', ['chip_functions_invalid']],
      ['<1> <0>', 'OP_IF OP_ELSE <1> OP_BEGIN OP_UNTIL OP_ENDIF', 'OP_IF, OP_ELSE: Nested <1> OP_BEGIN OP_UNTIL', ['chip_loops']],
      ['<1> <0>', 'OP_IF OP_ELSE OP_ELSE OP_ELSE <1> OP_BEGIN OP_UNTIL OP_ENDIF', 'OP_IF, OP_ELSE (x3): Nested <1> OP_BEGIN OP_UNTIL', ['chip_loops']],
      ['<1> <0>', 'OP_IF OP_ELSE <0> OP_BEGIN OP_UNTIL OP_ENDIF', 'OP_IF, OP_ELSE: Nested <0> OP_BEGIN OP_UNTIL', ['chip_loops_invalid']],
      ['<1> <0>', 'OP_IF OP_ELSE <1> OP_BEGIN OP_ENDIF OP_UNTIL', 'OP_IF, OP_ELSE: Nested <1> OP_BEGIN OP_UNTIL, external OP_UNTIL', ['chip_loops_invalid']],
      ['<1> <0>', 'OP_IF <1> OP_BEGIN OP_ELSE <1> OP_BEGIN OP_UNTIL OP_ENDIF', 'OP_IF, OP_ELSE: Nested <1> OP_BEGIN OP_UNTIL, matching OP_BEGINs', ['chip_loops_invalid']],

      ['<1> <0>', 'OP_NOTIF OP_IF <3> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_NOTIF: Nested OP_IF (3 == 3)', []],
      ['<1> <0>', 'OP_NOTIF OP_IF <0> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_NOTIF: Nested OP_IF (0 == 3)', ['invalid']],
      ['<0> <0>', 'OP_NOTIF OP_NOTIF <3> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_NOTIF: Nested OP_NOTIF (3 == 3)', []],
      ['<0> <0>', 'OP_NOTIF OP_NOTIF <0> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_NOTIF: Nested OP_NOTIF (0 == 3)', ['invalid']],
      ['<0>', 'OP_NOTIF <<3>> OP_EVAL OP_ENDIF <3> OP_EQUAL', 'OP_NOTIF: Nested OP_EVAL (3 == 3)', ['chip_eval']],
      ['<0>', 'OP_NOTIF <<3>> OP_EVAL OP_ENDIF <2> OP_EQUAL', 'OP_NOTIF: Nested OP_EVAL (2 == 3)', ['chip_eval_invalid']],
      ['<0>', 'OP_NOTIF <<3>> <0> OP_TUCK OP_DEFINE OP_INVOKE OP_ENDIF <3> OP_EQUAL', 'OP_NOTIF: Nested define/invoke (3 == 3)', ['chip_functions']],
      ['<0>', 'OP_NOTIF <<3>> <0> OP_TUCK OP_DEFINE OP_INVOKE OP_ENDIF <2> OP_EQUAL', 'OP_NOTIF: Nested define/invoke (2 == 3)', ['chip_functions_invalid']],
      ['<1> <0>', 'OP_NOTIF <1> OP_BEGIN OP_UNTIL OP_ENDIF', 'OP_NOTIF: Nested <1> OP_BEGIN OP_UNTIL', ['chip_loops']],
      ['<1> <0>', 'OP_NOTIF <0> OP_BEGIN OP_UNTIL OP_ENDIF', 'OP_NOTIF: Nested <0> OP_BEGIN OP_UNTIL', ['chip_loops_invalid']],
      ['<1> <0>', 'OP_NOTIF <1> OP_BEGIN OP_ENDIF OP_UNTIL', 'OP_NOTIF: Nested <1> OP_BEGIN OP_UNTIL, external OP_UNTIL', ['chip_loops_invalid']],

      ['<1> <1>', 'OP_NOTIF OP_ELSE OP_IF <3> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_NOTIF, OP_ELSE: Nested OP_IF (3 == 3)', []],
      ['<1> <1>', 'OP_NOTIF OP_ELSE OP_IF <0> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_NOTIF, OP_ELSE: Nested OP_IF (0 == 3)', ['invalid']],
      ['<0> <1>', 'OP_NOTIF OP_ELSE OP_NOTIF <3> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_NOTIF, OP_ELSE: Nested OP_NOTIF (3 == 3)', []],
      ['<0> <1>', 'OP_NOTIF OP_ELSE OP_NOTIF <0> OP_ENDIF OP_ENDIF <3> OP_EQUAL', 'OP_NOTIF, OP_ELSE: Nested OP_NOTIF (0 == 3)', ['invalid']],
      ['<1>', 'OP_NOTIF OP_ELSE <<3>> OP_EVAL OP_ENDIF <3> OP_EQUAL', 'OP_NOTIF, OP_ELSE: Nested OP_EVAL (3 == 3)', ['chip_eval']],
      ['<1>', 'OP_NOTIF OP_ELSE OP_ELSE OP_ELSE <<3>> OP_EVAL OP_ENDIF <3> OP_EQUAL', 'OP_NOTIF, OP_ELSE (x3): Nested OP_EVAL (3 == 3)', ['chip_eval']],
      ['<1>', 'OP_NOTIF OP_ELSE <<3>> OP_EVAL OP_ENDIF <2> OP_EQUAL', 'OP_NOTIF, OP_ELSE: Nested OP_EVAL (2 == 3)', ['chip_eval_invalid']],
      ['<1>', 'OP_NOTIF OP_ELSE <<3>> <0> OP_TUCK OP_DEFINE OP_INVOKE OP_ENDIF <3> OP_EQUAL', 'OP_NOTIF, OP_ELSE: Nested define/invoke (3 == 3)', ['chip_functions']],
      ['<1>', 'OP_NOTIF OP_ELSE OP_ELSE OP_ELSE <<3>> <0> OP_TUCK OP_DEFINE OP_INVOKE OP_ENDIF <3> OP_EQUAL', 'OP_NOTIF, OP_ELSE (x3): Nested define/invoke (3 == 3)', ['chip_functions']],
      ['<1>', 'OP_NOTIF OP_ELSE <<3>> <0> OP_TUCK OP_DEFINE OP_INVOKE OP_ENDIF <2> OP_EQUAL', 'OP_NOTIF, OP_ELSE: Nested define/invoke (2 == 3)', ['chip_functions_invalid']],
      ['<1> <1>', 'OP_NOTIF OP_ELSE <1> OP_BEGIN OP_UNTIL OP_ENDIF', 'OP_NOTIF, OP_ELSE: Nested <1> OP_BEGIN OP_UNTIL', ['chip_loops']],
      ['<1> <1>', 'OP_NOTIF OP_ELSE OP_ELSE OP_ELSE <1> OP_BEGIN OP_UNTIL OP_ENDIF', 'OP_NOTIF, OP_ELSE (x3): Nested <1> OP_BEGIN OP_UNTIL', ['chip_loops']],
      ['<1> <1>', 'OP_NOTIF OP_ELSE <0> OP_BEGIN OP_UNTIL OP_ENDIF', 'OP_NOTIF, OP_ELSE: Nested <0> OP_BEGIN OP_UNTIL', ['chip_loops_invalid']],
      ['<1> <1>', 'OP_NOTIF OP_ELSE <1> OP_BEGIN OP_ENDIF OP_UNTIL', 'OP_NOTIF, OP_ELSE: Nested <1> OP_BEGIN OP_UNTIL, external OP_UNTIL', ['chip_loops_invalid']],
      ['<1> <1>', 'OP_NOTIF <1> OP_BEGIN OP_ELSE <1> OP_BEGIN OP_UNTIL OP_ENDIF', 'OP_NOTIF, OP_ELSE: Nested <1> OP_BEGIN OP_UNTIL, matching OP_BEGINs', ['chip_loops_invalid']],

      ['', '<0> OP_EVAL OP_BEGIN <0> OP_EVAL <0> OP_IF OP_BEGIN <0> OP_EVAL <1> OP_UNTIL OP_ELSE <0> OP_NOTIF OP_BEGIN <OP_13> OP_EVAL <1> OP_UNTIL OP_ENDIF OP_ENDIF <1> OP_UNTIL <13> OP_EQUAL', 'Deeply nested flow control', ['chip_eval']],
      ['', '<0> <0> OP_TUCK OP_DEFINE OP_INVOKE OP_BEGIN <0> <1> OP_TUCK OP_DEFINE OP_INVOKE <0> OP_IF OP_BEGIN <0> <2> OP_TUCK OP_DEFINE OP_INVOKE <1> OP_UNTIL OP_ELSE <0> OP_NOTIF OP_BEGIN <OP_13> <3> OP_TUCK OP_DEFINE OP_INVOKE <1> OP_UNTIL OP_ENDIF OP_ENDIF <1> OP_UNTIL <13> OP_EQUAL', 'Deeply nested flow control', ['chip_functions']],
    ],
  ],
] as const satisfies VmbTestDefinitionGroup[];
