import type { VmbTestDefinitionGroup } from '../../lib.js';
import { allZeros, binaryOpcodes, justZeroAndOne, positiveZeros, smallZerosAndOnes, ternaryOpcodes, unaryOpcodes, zerosAndOnes } from '../bch-vmb-test-mixins.bigint.js';
import { repeat } from '../bch-vmb-test-mixins.js';
import { generateTestCases, setExpectedResults } from '../bch-vmb-test-utils.js';

// TODO: test acceptance of smallZerosAndOnes for all ops

// TODO: generate seeded-random test vectors for all ops

// TODO: OP_NOT & OP_0NOTEQUAL

/* TODO: OP_NUMEQUALVERIFY (for completeness) */

export default [
  [
    'BigInt',
    [
      ...setExpectedResults(generateTestCases(['<$0>', '', '$0 is truthy'], [zerosAndOnes]), {
        'negative one is truthy': [],
        'negative zero is truthy': ['invalid'],
        'one is truthy': ['skip'],
        'padded negative one (520 bytes) is truthy': [],
        'padded negative one (521 bytes) is truthy': ['chip_bigint'],
        'padded negative one is truthy': [],
        'padded negative zero (520 bytes) is truthy': ['invalid'],
        'padded negative zero (521 bytes) is truthy': ['chip_bigint_invalid'],
        'padded negative zero is truthy': ['invalid'],
        'padded one (520 bytes) is truthy': [],
        'padded one (521 bytes) is truthy': ['chip_bigint'],
        'padded one is truthy': [],
        'padded zero (520 bytes) is truthy': ['invalid'],
        'padded zero (521 bytes) is truthy': ['chip_bigint_invalid'],
        'padded zero is truthy': ['invalid'],
        'zero is truthy': ['skip'],
      }),
      ...setExpectedResults(generateTestCases(['', '$0 <1>', '$0 on empty stack'], [unaryOpcodes]), {
        'OP_0NOTEQUAL on empty stack': ['invalid'],
        'OP_1ADD on empty stack': ['invalid'],
        'OP_1SUB on empty stack': ['invalid'],
        'OP_ABS on empty stack': ['invalid'],
        'OP_BIN2NUM on empty stack': ['invalid'],
        'OP_NEGATE on empty stack': ['invalid'],
        'OP_NOT on empty stack': ['invalid'],
      }),
      [``, 'OP_BIN2NUM OP_NOT', 'OP_BIN2NUM OP_NOT on empty stack', ['invalid']],
      ...setExpectedResults(generateTestCases(['<$0>', '$1 <1>', '$1 on 1-item stack of $0'], [justZeroAndOne, [...binaryOpcodes, ...ternaryOpcodes]]), {
        'OP_0NOTEQUAL on 1-item stack of one': ['invalid'],
        'OP_0NOTEQUAL on 1-item stack of zero': ['invalid'],
        'OP_1ADD on 1-item stack of one': ['invalid'],
        'OP_1ADD on 1-item stack of zero': ['invalid'],
        'OP_1SUB on 1-item stack of one': ['invalid'],
        'OP_1SUB on 1-item stack of zero': ['invalid'],
        'OP_ABS on 1-item stack of one': ['invalid'],
        'OP_ABS on 1-item stack of zero': ['invalid'],
        'OP_ADD on 1-item stack of one': ['invalid'],
        'OP_ADD on 1-item stack of zero': ['invalid'],
        'OP_BIN2NUM on 1-item stack of one': ['invalid'],
        'OP_BIN2NUM on 1-item stack of zero': ['invalid'],
        'OP_BOOLAND on 1-item stack of one': ['invalid'],
        'OP_BOOLAND on 1-item stack of zero': ['invalid'],
        'OP_BOOLOR on 1-item stack of one': ['invalid'],
        'OP_BOOLOR on 1-item stack of zero': ['invalid'],
        'OP_DIV on 1-item stack of one': ['invalid'],
        'OP_DIV on 1-item stack of zero': ['invalid'],
        'OP_GREATERTHAN on 1-item stack of one': ['invalid'],
        'OP_GREATERTHAN on 1-item stack of zero': ['invalid'],
        'OP_GREATERTHANOREQUAL on 1-item stack of one': ['invalid'],
        'OP_GREATERTHANOREQUAL on 1-item stack of zero': ['invalid'],
        'OP_LESSTHAN on 1-item stack of one': ['invalid'],
        'OP_LESSTHAN on 1-item stack of zero': ['invalid'],
        'OP_LESSTHANOREQUAL on 1-item stack of one': ['invalid'],
        'OP_LESSTHANOREQUAL on 1-item stack of zero': ['invalid'],
        'OP_MAX on 1-item stack of one': ['invalid'],
        'OP_MAX on 1-item stack of zero': ['invalid'],
        'OP_MIN on 1-item stack of one': ['invalid'],
        'OP_MIN on 1-item stack of zero': ['invalid'],
        'OP_MOD on 1-item stack of one': ['invalid'],
        'OP_MOD on 1-item stack of zero': ['invalid'],
        'OP_MUL on 1-item stack of one': ['invalid'],
        'OP_MUL on 1-item stack of zero': ['invalid'],
        'OP_NEGATE on 1-item stack of one': ['invalid'],
        'OP_NEGATE on 1-item stack of zero': ['invalid'],
        'OP_NOT on 1-item stack of one': ['invalid'],
        'OP_NOT on 1-item stack of zero': ['invalid'],
        'OP_NUM2BIN on 1-item stack of one': ['invalid'],
        'OP_NUM2BIN on 1-item stack of zero': ['invalid'],
        'OP_NUMEQUAL on 1-item stack of one': ['invalid'],
        'OP_NUMEQUAL on 1-item stack of zero': ['invalid'],
        'OP_NUMEQUALVERIFY on 1-item stack of one': ['invalid'],
        'OP_NUMEQUALVERIFY on 1-item stack of zero': ['invalid'],
        'OP_NUMNOTEQUAL on 1-item stack of one': ['invalid'],
        'OP_NUMNOTEQUAL on 1-item stack of zero': ['invalid'],
        'OP_SUB on 1-item stack of one': ['invalid'],
        'OP_SUB on 1-item stack of zero': ['invalid'],
        'OP_WITHIN on 1-item stack of one': ['invalid'],
        'OP_WITHIN on 1-item stack of zero': ['invalid'],
      }),
      ...setExpectedResults(generateTestCases(['<$0> <$1>', '$2 <1>', '$2 on 2-item stack of $0 and $1'], [justZeroAndOne, justZeroAndOne, ternaryOpcodes]), {
        'OP_WITHIN on 2-item stack of one and one': ['invalid'],
        'OP_WITHIN on 2-item stack of one and zero': ['invalid'],
        'OP_WITHIN on 2-item stack of zero and one': ['invalid'],
        'OP_WITHIN on 2-item stack of zero and zero': ['invalid'],
      }),

      /* OP_BIN2NUM */
      ...setExpectedResults(generateTestCases(['<$0>', '<$1> OP_BIN2NUM OP_EQUAL', 'OP_BIN2NUM $1 is $0'], [smallZerosAndOnes, zerosAndOnes]), {
        'OP_BIN2NUM negative one is negative one': [],
        'OP_BIN2NUM negative one is negative zero': ['invalid'],
        'OP_BIN2NUM negative one is one': ['invalid'],
        'OP_BIN2NUM negative one is padded negative one': ['invalid'],
        'OP_BIN2NUM negative one is padded negative zero': ['invalid'],
        'OP_BIN2NUM negative one is padded one': ['invalid'],
        'OP_BIN2NUM negative one is padded zero': ['invalid'],
        'OP_BIN2NUM negative one is zero': ['invalid'],
        'OP_BIN2NUM negative zero is negative one': ['invalid'],
        'OP_BIN2NUM negative zero is negative zero': ['invalid'],
        'OP_BIN2NUM negative zero is one': ['invalid'],
        'OP_BIN2NUM negative zero is padded negative one': ['invalid'],
        'OP_BIN2NUM negative zero is padded negative zero': ['invalid'],
        'OP_BIN2NUM negative zero is padded one': ['invalid'],
        'OP_BIN2NUM negative zero is padded zero': ['invalid'],
        'OP_BIN2NUM negative zero is zero': [],
        'OP_BIN2NUM one is negative one': ['invalid'],
        'OP_BIN2NUM one is negative zero': ['invalid'],
        'OP_BIN2NUM one is one': [],
        'OP_BIN2NUM one is padded negative one': ['invalid'],
        'OP_BIN2NUM one is padded negative zero': ['invalid'],
        'OP_BIN2NUM one is padded one': ['invalid'],
        'OP_BIN2NUM one is padded zero': ['invalid'],
        'OP_BIN2NUM one is zero': ['invalid'],
        'OP_BIN2NUM padded negative one (520 bytes) is negative one': ['2023_p2sh_invalid'],
        'OP_BIN2NUM padded negative one (520 bytes) is negative zero': ['invalid'],
        'OP_BIN2NUM padded negative one (520 bytes) is one': ['invalid'],
        'OP_BIN2NUM padded negative one (520 bytes) is padded negative one': ['invalid'],
        'OP_BIN2NUM padded negative one (520 bytes) is padded negative zero': ['invalid'],
        'OP_BIN2NUM padded negative one (520 bytes) is padded one': ['invalid'],
        'OP_BIN2NUM padded negative one (520 bytes) is padded zero': ['invalid'],
        'OP_BIN2NUM padded negative one (520 bytes) is zero': ['invalid'],
        'OP_BIN2NUM padded negative one (521 bytes) is negative one': ['chip_bigint'],
        'OP_BIN2NUM padded negative one (521 bytes) is negative zero': ['invalid'],
        'OP_BIN2NUM padded negative one (521 bytes) is one': ['invalid'],
        'OP_BIN2NUM padded negative one (521 bytes) is padded negative one': ['invalid'],
        'OP_BIN2NUM padded negative one (521 bytes) is padded negative zero': ['invalid'],
        'OP_BIN2NUM padded negative one (521 bytes) is padded one': ['invalid'],
        'OP_BIN2NUM padded negative one (521 bytes) is padded zero': ['invalid'],
        'OP_BIN2NUM padded negative one (521 bytes) is zero': ['invalid'],
        'OP_BIN2NUM padded negative one is negative one': [],
        'OP_BIN2NUM padded negative one is negative zero': ['invalid'],
        'OP_BIN2NUM padded negative one is one': ['invalid'],
        'OP_BIN2NUM padded negative one is padded negative one': ['invalid'],
        'OP_BIN2NUM padded negative one is padded negative zero': ['invalid'],
        'OP_BIN2NUM padded negative one is padded one': ['invalid'],
        'OP_BIN2NUM padded negative one is padded zero': ['invalid'],
        'OP_BIN2NUM padded negative one is zero': ['invalid'],
        'OP_BIN2NUM padded negative zero (520 bytes) is negative one': ['invalid'],
        'OP_BIN2NUM padded negative zero (520 bytes) is negative zero': ['invalid'],
        'OP_BIN2NUM padded negative zero (520 bytes) is one': ['invalid'],
        'OP_BIN2NUM padded negative zero (520 bytes) is padded negative one': ['invalid'],
        'OP_BIN2NUM padded negative zero (520 bytes) is padded negative zero': ['invalid'],
        'OP_BIN2NUM padded negative zero (520 bytes) is padded one': ['invalid'],
        'OP_BIN2NUM padded negative zero (520 bytes) is padded zero': ['invalid'],
        'OP_BIN2NUM padded negative zero (520 bytes) is zero': ['2023_p2sh_invalid'],
        'OP_BIN2NUM padded negative zero (521 bytes) is negative one': ['invalid'],
        'OP_BIN2NUM padded negative zero (521 bytes) is negative zero': ['invalid'],
        'OP_BIN2NUM padded negative zero (521 bytes) is one': ['invalid'],
        'OP_BIN2NUM padded negative zero (521 bytes) is padded negative one': ['invalid'],
        'OP_BIN2NUM padded negative zero (521 bytes) is padded negative zero': ['invalid'],
        'OP_BIN2NUM padded negative zero (521 bytes) is padded one': ['invalid'],
        'OP_BIN2NUM padded negative zero (521 bytes) is padded zero': ['invalid'],
        'OP_BIN2NUM padded negative zero (521 bytes) is zero': ['chip_bigint'],
        'OP_BIN2NUM padded negative zero is negative one': ['invalid'],
        'OP_BIN2NUM padded negative zero is negative zero': ['invalid'],
        'OP_BIN2NUM padded negative zero is one': ['invalid'],
        'OP_BIN2NUM padded negative zero is padded negative one': ['invalid'],
        'OP_BIN2NUM padded negative zero is padded negative zero': ['invalid'],
        'OP_BIN2NUM padded negative zero is padded one': ['invalid'],
        'OP_BIN2NUM padded negative zero is padded zero': ['invalid'],
        'OP_BIN2NUM padded negative zero is zero': [],
        'OP_BIN2NUM padded one (520 bytes) is negative one': ['invalid'],
        'OP_BIN2NUM padded one (520 bytes) is negative zero': ['invalid'],
        'OP_BIN2NUM padded one (520 bytes) is one': ['2023_p2sh_invalid'],
        'OP_BIN2NUM padded one (520 bytes) is padded negative one': ['invalid'],
        'OP_BIN2NUM padded one (520 bytes) is padded negative zero': ['invalid'],
        'OP_BIN2NUM padded one (520 bytes) is padded one': ['invalid'],
        'OP_BIN2NUM padded one (520 bytes) is padded zero': ['invalid'],
        'OP_BIN2NUM padded one (520 bytes) is zero': ['invalid'],
        'OP_BIN2NUM padded one (521 bytes) is negative one': ['invalid'],
        'OP_BIN2NUM padded one (521 bytes) is negative zero': ['invalid'],
        'OP_BIN2NUM padded one (521 bytes) is one': ['chip_bigint'],
        'OP_BIN2NUM padded one (521 bytes) is padded negative one': ['invalid'],
        'OP_BIN2NUM padded one (521 bytes) is padded negative zero': ['invalid'],
        'OP_BIN2NUM padded one (521 bytes) is padded one': ['invalid'],
        'OP_BIN2NUM padded one (521 bytes) is padded zero': ['invalid'],
        'OP_BIN2NUM padded one (521 bytes) is zero': ['invalid'],
        'OP_BIN2NUM padded one is negative one': ['invalid'],
        'OP_BIN2NUM padded one is negative zero': ['invalid'],
        'OP_BIN2NUM padded one is one': [],
        'OP_BIN2NUM padded one is padded negative one': ['invalid'],
        'OP_BIN2NUM padded one is padded negative zero': ['invalid'],
        'OP_BIN2NUM padded one is padded one': ['invalid'],
        'OP_BIN2NUM padded one is padded zero': ['invalid'],
        'OP_BIN2NUM padded one is zero': ['invalid'],
        'OP_BIN2NUM padded zero (520 bytes) is negative one': ['invalid'],
        'OP_BIN2NUM padded zero (520 bytes) is negative zero': ['invalid'],
        'OP_BIN2NUM padded zero (520 bytes) is one': ['invalid'],
        'OP_BIN2NUM padded zero (520 bytes) is padded negative one': ['invalid'],
        'OP_BIN2NUM padded zero (520 bytes) is padded negative zero': ['invalid'],
        'OP_BIN2NUM padded zero (520 bytes) is padded one': ['invalid'],
        'OP_BIN2NUM padded zero (520 bytes) is padded zero': ['invalid'],
        'OP_BIN2NUM padded zero (520 bytes) is zero': ['2023_p2sh_invalid'],
        'OP_BIN2NUM padded zero (521 bytes) is negative one': ['invalid'],
        'OP_BIN2NUM padded zero (521 bytes) is negative zero': ['invalid'],
        'OP_BIN2NUM padded zero (521 bytes) is one': ['invalid'],
        'OP_BIN2NUM padded zero (521 bytes) is padded negative one': ['invalid'],
        'OP_BIN2NUM padded zero (521 bytes) is padded negative zero': ['invalid'],
        'OP_BIN2NUM padded zero (521 bytes) is padded one': ['invalid'],
        'OP_BIN2NUM padded zero (521 bytes) is padded zero': ['invalid'],
        'OP_BIN2NUM padded zero (521 bytes) is zero': ['chip_bigint'],
        'OP_BIN2NUM padded zero is negative one': ['invalid'],
        'OP_BIN2NUM padded zero is negative zero': ['invalid'],
        'OP_BIN2NUM padded zero is one': ['invalid'],
        'OP_BIN2NUM padded zero is padded negative one': ['invalid'],
        'OP_BIN2NUM padded zero is padded negative zero': ['invalid'],
        'OP_BIN2NUM padded zero is padded one': ['invalid'],
        'OP_BIN2NUM padded zero is padded zero': ['invalid'],
        'OP_BIN2NUM padded zero is zero': [],
        'OP_BIN2NUM zero is negative one': ['invalid'],
        'OP_BIN2NUM zero is negative zero': ['invalid'],
        'OP_BIN2NUM zero is one': ['invalid'],
        'OP_BIN2NUM zero is padded negative one': ['invalid'],
        'OP_BIN2NUM zero is padded negative zero': ['invalid'],
        'OP_BIN2NUM zero is padded one': ['invalid'],
        'OP_BIN2NUM zero is padded zero': ['invalid'],
        'OP_BIN2NUM zero is zero': [],
      }),
      ...setExpectedResults(generateTestCases(['<$0>', 'OP_BIN2NUM', 'OP_BIN2NUM $0 is truthy'], [zerosAndOnes]), {
        'OP_BIN2NUM negative one is truthy': [],
        'OP_BIN2NUM negative zero is truthy': ['invalid'],
        'OP_BIN2NUM one is truthy': [],
        'OP_BIN2NUM padded negative one (520 bytes) is truthy': [],
        'OP_BIN2NUM padded negative one (521 bytes) is truthy': ['chip_bigint'],
        'OP_BIN2NUM padded negative one is truthy': [],
        'OP_BIN2NUM padded negative zero (520 bytes) is truthy': ['invalid'],
        'OP_BIN2NUM padded negative zero (521 bytes) is truthy': ['chip_bigint_invalid'],
        'OP_BIN2NUM padded negative zero is truthy': ['invalid'],
        'OP_BIN2NUM padded one (520 bytes) is truthy': [],
        'OP_BIN2NUM padded one (521 bytes) is truthy': ['chip_bigint'],
        'OP_BIN2NUM padded one is truthy': [],
        'OP_BIN2NUM padded zero (520 bytes) is truthy': ['invalid'],
        'OP_BIN2NUM padded zero (521 bytes) is truthy': ['chip_bigint_invalid'],
        'OP_BIN2NUM padded zero is truthy': ['invalid'],
        'OP_BIN2NUM zero is truthy': ['invalid'],
      }),
      ...setExpectedResults(generateTestCases(['<$0>', 'OP_NOT', 'OP_NOT $0 is truthy (without OP_BIN2NUM)'], [zerosAndOnes]), {
        'OP_NOT negative one is truthy (without OP_BIN2NUM)': ['invalid'],
        'OP_NOT negative zero is truthy (without OP_BIN2NUM)': ['invalid'],
        'OP_NOT one is truthy (without OP_BIN2NUM)': ['invalid'],
        'OP_NOT padded negative one (520 bytes) is truthy (without OP_BIN2NUM)': ['invalid'],
        'OP_NOT padded negative one (521 bytes) is truthy (without OP_BIN2NUM)': ['chip_bigint_invalid'],
        'OP_NOT padded negative one is truthy (without OP_BIN2NUM)': ['invalid'],
        'OP_NOT padded negative zero (520 bytes) is truthy (without OP_BIN2NUM)': ['invalid'],
        'OP_NOT padded negative zero (521 bytes) is truthy (without OP_BIN2NUM)': ['chip_bigint_invalid'],
        'OP_NOT padded negative zero is truthy (without OP_BIN2NUM)': ['invalid'],
        'OP_NOT padded one (520 bytes) is truthy (without OP_BIN2NUM)': ['invalid'],
        'OP_NOT padded one (521 bytes) is truthy (without OP_BIN2NUM)': ['chip_bigint_invalid'],
        'OP_NOT padded one is truthy (without OP_BIN2NUM)': ['invalid'],
        'OP_NOT padded zero (520 bytes) is truthy (without OP_BIN2NUM)': ['invalid'],
        'OP_NOT padded zero (521 bytes) is truthy (without OP_BIN2NUM)': ['chip_bigint_invalid'],
        'OP_NOT padded zero is truthy (without OP_BIN2NUM)': ['invalid'],
        'OP_NOT zero is truthy (without OP_BIN2NUM)': [],
      }),
      ...setExpectedResults(generateTestCases(['<$0>', 'OP_NOT OP_BIN2NUM', 'OP_NOT OP_BIN2NUM $0 is truthy'], [zerosAndOnes]), {
        'OP_NOT OP_BIN2NUM negative one is truthy': ['invalid'],
        'OP_NOT OP_BIN2NUM negative zero is truthy': ['invalid'],
        'OP_NOT OP_BIN2NUM one is truthy': ['invalid'],
        'OP_NOT OP_BIN2NUM padded negative one (520 bytes) is truthy': ['invalid'],
        'OP_NOT OP_BIN2NUM padded negative one (521 bytes) is truthy': ['chip_bigint_invalid'],
        'OP_NOT OP_BIN2NUM padded negative one is truthy': ['invalid'],
        'OP_NOT OP_BIN2NUM padded negative zero (520 bytes) is truthy': ['invalid'],
        'OP_NOT OP_BIN2NUM padded negative zero (521 bytes) is truthy': ['chip_bigint_invalid'],
        'OP_NOT OP_BIN2NUM padded negative zero is truthy': ['invalid'],
        'OP_NOT OP_BIN2NUM padded one (520 bytes) is truthy': ['invalid'],
        'OP_NOT OP_BIN2NUM padded one (521 bytes) is truthy': ['chip_bigint_invalid'],
        'OP_NOT OP_BIN2NUM padded one is truthy': ['invalid'],
        'OP_NOT OP_BIN2NUM padded zero (520 bytes) is truthy': ['invalid'],
        'OP_NOT OP_BIN2NUM padded zero (521 bytes) is truthy': ['chip_bigint_invalid'],
        'OP_NOT OP_BIN2NUM padded zero is truthy': ['invalid'],
        'OP_NOT OP_BIN2NUM zero is truthy': [],
      }),
      ...setExpectedResults(generateTestCases(['<$0>', 'OP_BIN2NUM OP_NOT', 'OP_BIN2NUM OP_NOT $0 is truthy'], [zerosAndOnes]), {
        'OP_BIN2NUM OP_NOT negative one is truthy': ['invalid'],
        'OP_BIN2NUM OP_NOT negative zero is truthy': [],
        'OP_BIN2NUM OP_NOT one is truthy': ['invalid'],
        'OP_BIN2NUM OP_NOT padded negative one (520 bytes) is truthy': ['invalid'],
        'OP_BIN2NUM OP_NOT padded negative one (521 bytes) is truthy': ['chip_bigint_invalid'],
        'OP_BIN2NUM OP_NOT padded negative one is truthy': ['invalid'],
        'OP_BIN2NUM OP_NOT padded negative zero (520 bytes) is truthy': [],
        'OP_BIN2NUM OP_NOT padded negative zero (521 bytes) is truthy': ['chip_bigint'],
        'OP_BIN2NUM OP_NOT padded negative zero is truthy': [],
        'OP_BIN2NUM OP_NOT padded one (520 bytes) is truthy': ['invalid'],
        'OP_BIN2NUM OP_NOT padded one (521 bytes) is truthy': ['chip_bigint_invalid'],
        'OP_BIN2NUM OP_NOT padded one is truthy': ['invalid'],
        'OP_BIN2NUM OP_NOT padded zero (520 bytes) is truthy': [],
        'OP_BIN2NUM OP_NOT padded zero (521 bytes) is truthy': ['chip_bigint'],
        'OP_BIN2NUM OP_NOT padded zero is truthy': [],
        'OP_BIN2NUM OP_NOT zero is truthy': [],
      }),

      [`<0x12b4> <0x1234 0x80>`, 'OP_BIN2NUM OP_EQUAL', 'OP_BIN2NUM Non-minimal negative number'],
      [`<0x0100000000000000000000000000000000000000000000000000000000000000000000003ba3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa4b1e5e4a29ab5f49ffff001d1dac2b7c>`, 'OP_HASH256 OP_1ADD', 'OP_1ADD genesis block header hash without OP_BIN2NUM', ['chip_bigint_invalid']],
      [`<0x0100000000000000000000000000000000000000000000000000000000000000000000003ba3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa4b1e5e4a29ab5f49ffff001d1dac2b7c>`, 'OP_HASH256 OP_BIN2NUM OP_1ADD', 'OP_1ADD genesis block header hash with OP_BIN2NUM', ['chip_bigint']],

      /* OP_NUM2BIN */
      ...setExpectedResults(generateTestCases(['<$0>', '<$1> <$2> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN $1 with length of $2 is $0'], [positiveZeros, allZeros, zerosAndOnes]), {
        'OP_NUM2BIN negative zero with length of negative one is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of negative one is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of negative zero is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of one is padded zero': [],
        'OP_NUM2BIN negative zero with length of one is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded negative one is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative one is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative zero is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded one is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded one is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded zero is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded zero is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of zero is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of zero is zero': [],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of negative one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of one is padded zero': ['2023_p2sh_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded one is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded zero is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of zero is zero': ['2023_p2sh_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of negative one is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of negative one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of negative zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of negative zero is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of one is padded zero': ['chip_bigint'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative one (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative one (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative one is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative zero (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative zero (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative zero is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded one (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded one (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded one is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded zero (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded zero (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded zero is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of zero is zero': ['chip_bigint'],
        'OP_NUM2BIN padded negative zero with length of negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of negative one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of one is padded zero': [],
        'OP_NUM2BIN padded negative zero with length of one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded one is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded zero is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of zero is zero': [],
        'OP_NUM2BIN padded zero (520 bytes) with length of negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of negative one is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of one is padded zero': ['2023_p2sh_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of one is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative one is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded one is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded one is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded zero is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of zero is zero': ['2023_p2sh_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of negative one is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of negative one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of negative zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of negative zero is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of one is padded zero': ['chip_bigint'],
        'OP_NUM2BIN padded zero (521 bytes) with length of one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative one (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative one (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative one is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative zero (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative zero (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative zero is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded one (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded one (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded one is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded zero (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded zero (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded zero is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of zero is zero': ['chip_bigint'],
        'OP_NUM2BIN padded zero with length of negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of negative one is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of one is padded zero': [],
        'OP_NUM2BIN padded zero with length of one is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative one is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded one is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded one is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded zero is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of zero is zero': [],
        'OP_NUM2BIN zero with length of negative one is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of negative one is zero': ['invalid'],
        'OP_NUM2BIN zero with length of negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of negative zero is zero': ['invalid'],
        'OP_NUM2BIN zero with length of one is padded zero': [],
        'OP_NUM2BIN zero with length of one is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded negative one is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative one is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative zero is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded one is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded one is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded zero is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded zero is zero': ['invalid'],
        'OP_NUM2BIN zero with length of zero is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of zero is zero': [],
      }),

      ['<520>', '<0> <520> OP_NUM2BIN OP_SIZE OP_NIP OP_EQUAL', 'OP_NUM2BIN of 520 bytes'],
      ['<521>', '<0> <521> OP_NUM2BIN OP_SIZE OP_NIP OP_EQUAL', 'OP_NUM2BIN of 521 bytes', ['chip_bigint']],
      ['<10000>', '<0> <10000> OP_NUM2BIN OP_SIZE OP_NIP OP_EQUAL', 'OP_NUM2BIN of 10,000 bytes', ['chip_bigint']],
      ['<10001>', '<0> <10001> OP_NUM2BIN OP_SIZE OP_NIP OP_EQUAL', 'OP_NUM2BIN of 10,001 bytes', ['chip_bigint_invalid']],

      ['<0x1234000000000000>', '<0x1234> <8> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN retains endianness and appends padding'],
      ['<0x0012340000000000>', '<0x001234> <8> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN numbers beginning with 0x00'],
      ['<0x001234>', 'OP_DUP <8> OP_NUM2BIN OP_BIN2NUM OP_EQUAL', 'OP_NUM2BIN then OP_BIN2NUM numbers beginning with 0x00'],
      ['<0x1234000000000000>', '<0x123400> <8> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN accepts padded numbers'],
      ['<0x123400>', 'OP_DUP <8> OP_NUM2BIN OP_BIN2NUM OP_EQUAL', 'OP_NUM2BIN padded number then OP_BIN2NUM is not equal (fail)', ['invalid']],
      ['<0x123400>', 'OP_DUP <8> OP_NUM2BIN OP_BIN2NUM OP_NUMNOTEQUAL', 'OP_NUM2BIN padded number then OP_BIN2NUM, OP_NUMNOTEQUAL requires minimal encoding (fail)', ['invalid']],
      ['<0x123400>', 'OP_DUP <8> OP_NUM2BIN OP_BIN2NUM OP_EQUAL OP_NOT', 'OP_NUM2BIN padded number then OP_BIN2NUM is not equal (succeed)'],

      ['<256>', '<0> <0x0001> OP_NUM2BIN OP_SIZE OP_NIP OP_EQUAL', 'OP_NUM2BIN 0 with length of 256'],
      [`<0x1234 ${repeat('0x00', 125)}>`, '<13330> <127> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN positive integer length of 127'],
      [`<0x1234 ${repeat('0x00', 126)}>`, '<13330> <128> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN positive integer length of 128'],
      [`<0x1234 ${repeat('0x00', 518)}>`, '<13330> <520> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN positive integer length of 520'],
      [`<0x1234 ${repeat('0x00', 519)}>`, '<13330> <521> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN positive integer length of 521', ['chip_bigint']],
      [`<0x12b4>`, '<0x1234 0x80> <2> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN reduce-able negative integer'],
      [`<0x1234 ${repeat('0x00', 124)} 0x80>`, '<0x12b4> <127> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN negative integer length of 127'],
      [`<0x1234 ${repeat('0x00', 125)} 0x80>`, '<-13330> <128> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN negative integer length of 128'],
      [`<0x1234 ${repeat('0x00', 517)} 0x80>`, '<-13330> <520> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN negative integer length of 520'],
      [`<0x1234 ${repeat('0x00', 518)} 0x80>`, '<-13330> <521> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN negative integer length of 521', ['chip_bigint']],
      [`<0x00 "cash" 0x00 ${repeat('0x00', 121)}>`, '<0x00 "cash" 0x00> <127> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN padded bytes length of 127'],
      [`<0x00 "cash" 0x00 ${repeat('0x00', 122)}>`, '<0x00 "cash" 0x00> <128> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN padded bytes length of 128'],
      [`<0x00 "cash" 0x00 ${repeat('0x00', 514)}>`, '<0x00 "cash" 0x00> <520> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN padded bytes length of 520'],
      [`<0x00 "cash" 0x00 ${repeat('0x00', 515)}>`, '<0x00 "cash" 0x00> <521> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN padded bytes length of 521', ['chip_bigint']],
    ],
  ],
] as const satisfies VmbTestDefinitionGroup[];
