import type { VmbTestDefinitionGroup } from '../../lib.js';
import { numNotEqualTests } from '../bch-vmb-test-mixins.bigint.js';
import { mapTestCases, setExpectedResults } from '../bch-vmb-test-utils.js';

export default [
  [
    'BigInt',
    [
      ...setExpectedResults(mapTestCases(['<$2>', '<$0> <$1> OP_NUMNOTEQUAL OP_EQUAL', 'OP_NUMNOTEQUAL $0 and $1'], numNotEqualTests, { prefixAsHexLiterals: true }), {
        'OP_NUMNOTEQUAL 1-byte number (all bits set) and 1-byte number (all bits set)': [],
        'OP_NUMNOTEQUAL 1-byte number (all bits set) and 4096-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 1-byte number (all bits set) and 512-byte number (all bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 1-byte number (all bits set) and 64-byte number (all bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 1-byte number (all bits set) and 8-byte number (all bits set)': [],
        'OP_NUMNOTEQUAL 1-byte number (all bits set) and 8192-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 1-byte number (alternating bits set) and 1-byte number (alternating bits set)': [],
        'OP_NUMNOTEQUAL 1-byte number (alternating bits set) and 4096-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 1-byte number (alternating bits set) and 512-byte number (alternating bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 1-byte number (alternating bits set) and 64-byte number (alternating bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 1-byte number (alternating bits set) and 8-byte number (alternating bits set)': [],
        'OP_NUMNOTEQUAL 1-byte number (alternating bits set) and 8192-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 1-byte number (highest-bit set) and 1-byte number (highest-bit set)': [],
        'OP_NUMNOTEQUAL 1-byte number (highest-bit set) and 4096-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 1-byte number (highest-bit set) and 512-byte number (highest-bit set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 1-byte number (highest-bit set) and 64-byte number (highest-bit set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 1-byte number (highest-bit set) and 8-byte number (highest-bit set)': [],
        'OP_NUMNOTEQUAL 1-byte number (highest-bit set) and 8192-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 1-byte number (one bit set per byte) and 1-byte number (one bit set per byte)': ['skip'],
        'OP_NUMNOTEQUAL 1-byte number (one bit set per byte) and 4096-byte number (one bit set per byte)': ['skip'],
        'OP_NUMNOTEQUAL 1-byte number (one bit set per byte) and 512-byte number (one bit set per byte)': ['skip'],
        'OP_NUMNOTEQUAL 1-byte number (one bit set per byte) and 64-byte number (one bit set per byte)': ['skip'],
        'OP_NUMNOTEQUAL 1-byte number (one bit set per byte) and 8-byte number (one bit set per byte)': ['skip'],
        'OP_NUMNOTEQUAL 1-byte number (one bit set per byte) and 8192-byte number (one bit set per byte)': ['skip'],
        'OP_NUMNOTEQUAL 4096-byte number (all bits set) and 1-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (all bits set) and 4096-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (all bits set) and 512-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (all bits set) and 64-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (all bits set) and 8-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (all bits set) and 8192-byte number (all bits set)': ['chip_bigint_invalid'],
        'OP_NUMNOTEQUAL 4096-byte number (alternating bits set) and 1-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (alternating bits set) and 4096-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (alternating bits set) and 512-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (alternating bits set) and 64-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (alternating bits set) and 8-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (alternating bits set) and 8192-byte number (alternating bits set)': ['chip_bigint_invalid'],
        'OP_NUMNOTEQUAL 4096-byte number (highest-bit set) and 1-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (highest-bit set) and 4096-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (highest-bit set) and 512-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (highest-bit set) and 64-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (highest-bit set) and 8-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (highest-bit set) and 8192-byte number (highest-bit set)': ['chip_bigint_invalid'],
        'OP_NUMNOTEQUAL 4096-byte number (one bit set per byte) and 1-byte number (one bit set per byte)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (one bit set per byte) and 4096-byte number (one bit set per byte)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (one bit set per byte) and 512-byte number (one bit set per byte)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (one bit set per byte) and 64-byte number (one bit set per byte)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (one bit set per byte) and 8-byte number (one bit set per byte)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 4096-byte number (one bit set per byte) and 8192-byte number (one bit set per byte)': ['chip_bigint_invalid'],
        'OP_NUMNOTEQUAL 512-byte number (all bits set) and 1-byte number (all bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (all bits set) and 4096-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 512-byte number (all bits set) and 512-byte number (all bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (all bits set) and 64-byte number (all bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (all bits set) and 8-byte number (all bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (all bits set) and 8192-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 512-byte number (alternating bits set) and 1-byte number (alternating bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (alternating bits set) and 4096-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 512-byte number (alternating bits set) and 512-byte number (alternating bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (alternating bits set) and 64-byte number (alternating bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (alternating bits set) and 8-byte number (alternating bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (alternating bits set) and 8192-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 512-byte number (highest-bit set) and 1-byte number (highest-bit set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (highest-bit set) and 4096-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 512-byte number (highest-bit set) and 512-byte number (highest-bit set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (highest-bit set) and 64-byte number (highest-bit set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (highest-bit set) and 8-byte number (highest-bit set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (highest-bit set) and 8192-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 512-byte number (one bit set per byte) and 1-byte number (one bit set per byte)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (one bit set per byte) and 4096-byte number (one bit set per byte)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 512-byte number (one bit set per byte) and 512-byte number (one bit set per byte)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (one bit set per byte) and 64-byte number (one bit set per byte)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (one bit set per byte) and 8-byte number (one bit set per byte)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 512-byte number (one bit set per byte) and 8192-byte number (one bit set per byte)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 64-byte number (all bits set) and 1-byte number (all bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (all bits set) and 4096-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 64-byte number (all bits set) and 512-byte number (all bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (all bits set) and 64-byte number (all bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (all bits set) and 8-byte number (all bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (all bits set) and 8192-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 64-byte number (alternating bits set) and 1-byte number (alternating bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (alternating bits set) and 4096-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 64-byte number (alternating bits set) and 512-byte number (alternating bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (alternating bits set) and 64-byte number (alternating bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (alternating bits set) and 8-byte number (alternating bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (alternating bits set) and 8192-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 64-byte number (highest-bit set) and 1-byte number (highest-bit set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (highest-bit set) and 4096-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 64-byte number (highest-bit set) and 512-byte number (highest-bit set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (highest-bit set) and 64-byte number (highest-bit set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (highest-bit set) and 8-byte number (highest-bit set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (highest-bit set) and 8192-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 64-byte number (one bit set per byte) and 1-byte number (one bit set per byte)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (one bit set per byte) and 4096-byte number (one bit set per byte)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 64-byte number (one bit set per byte) and 512-byte number (one bit set per byte)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (one bit set per byte) and 64-byte number (one bit set per byte)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (one bit set per byte) and 8-byte number (one bit set per byte)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 64-byte number (one bit set per byte) and 8192-byte number (one bit set per byte)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8-byte number (all bits set) and 1-byte number (all bits set)': [],
        'OP_NUMNOTEQUAL 8-byte number (all bits set) and 4096-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8-byte number (all bits set) and 512-byte number (all bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 8-byte number (all bits set) and 64-byte number (all bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 8-byte number (all bits set) and 8-byte number (all bits set)': [],
        'OP_NUMNOTEQUAL 8-byte number (all bits set) and 8192-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8-byte number (alternating bits set) and 1-byte number (alternating bits set)': [],
        'OP_NUMNOTEQUAL 8-byte number (alternating bits set) and 4096-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8-byte number (alternating bits set) and 512-byte number (alternating bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 8-byte number (alternating bits set) and 64-byte number (alternating bits set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 8-byte number (alternating bits set) and 8-byte number (alternating bits set)': [],
        'OP_NUMNOTEQUAL 8-byte number (alternating bits set) and 8192-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8-byte number (highest-bit set) and 1-byte number (highest-bit set)': [],
        'OP_NUMNOTEQUAL 8-byte number (highest-bit set) and 4096-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8-byte number (highest-bit set) and 512-byte number (highest-bit set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 8-byte number (highest-bit set) and 64-byte number (highest-bit set)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 8-byte number (highest-bit set) and 8-byte number (highest-bit set)': [],
        'OP_NUMNOTEQUAL 8-byte number (highest-bit set) and 8192-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8-byte number (one bit set per byte) and 1-byte number (one bit set per byte)': [],
        'OP_NUMNOTEQUAL 8-byte number (one bit set per byte) and 4096-byte number (one bit set per byte)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8-byte number (one bit set per byte) and 512-byte number (one bit set per byte)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 8-byte number (one bit set per byte) and 64-byte number (one bit set per byte)': ['chip_bigint'],
        'OP_NUMNOTEQUAL 8-byte number (one bit set per byte) and 8-byte number (one bit set per byte)': [],
        'OP_NUMNOTEQUAL 8-byte number (one bit set per byte) and 8192-byte number (one bit set per byte)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (all bits set) and 1-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (all bits set) and 4096-byte number (all bits set)': ['chip_bigint_invalid'],
        'OP_NUMNOTEQUAL 8192-byte number (all bits set) and 512-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (all bits set) and 64-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (all bits set) and 8-byte number (all bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (all bits set) and 8192-byte number (all bits set)': ['chip_bigint_invalid'],
        'OP_NUMNOTEQUAL 8192-byte number (alternating bits set) and 1-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (alternating bits set) and 4096-byte number (alternating bits set)': ['chip_bigint_invalid'],
        'OP_NUMNOTEQUAL 8192-byte number (alternating bits set) and 512-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (alternating bits set) and 64-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (alternating bits set) and 8-byte number (alternating bits set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (alternating bits set) and 8192-byte number (alternating bits set)': ['chip_bigint_invalid'],
        'OP_NUMNOTEQUAL 8192-byte number (highest-bit set) and 1-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (highest-bit set) and 4096-byte number (highest-bit set)': ['chip_bigint_invalid'],
        'OP_NUMNOTEQUAL 8192-byte number (highest-bit set) and 512-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (highest-bit set) and 64-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (highest-bit set) and 8-byte number (highest-bit set)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (highest-bit set) and 8192-byte number (highest-bit set)': ['chip_bigint_invalid'],
        'OP_NUMNOTEQUAL 8192-byte number (one bit set per byte) and 1-byte number (one bit set per byte)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (one bit set per byte) and 4096-byte number (one bit set per byte)': ['chip_bigint_invalid'],
        'OP_NUMNOTEQUAL 8192-byte number (one bit set per byte) and 512-byte number (one bit set per byte)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (one bit set per byte) and 64-byte number (one bit set per byte)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (one bit set per byte) and 8-byte number (one bit set per byte)': ['chip_bigint', 'nonstandard'],
        'OP_NUMNOTEQUAL 8192-byte number (one bit set per byte) and 8192-byte number (one bit set per byte)': ['chip_bigint_invalid'],
      }),
    ],
  ],
] as const satisfies VmbTestDefinitionGroup[];
