import type { VmbTestDefinitionGroup } from '../../lib.js';
import { allZeros, positiveZeros, zerosAndOnes } from '../bch-vmb-test-mixins.bigint.js';
import { repeat } from '../bch-vmb-test-mixins.js';
import { generateTestCases, setExpectedResults } from '../bch-vmb-test-utils.js';

export default [
  [
    'BigInt',
    [
      ...setExpectedResults(generateTestCases(['<$0>', '<$1> <$2> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN $1 with length of $2 is $0'], [positiveZeros, allZeros, zerosAndOnes]), {
        'OP_NUM2BIN negative zero with length of negative one is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of negative one is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of negative zero is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of one is padded zero': [],
        'OP_NUM2BIN negative zero with length of one is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded negative one is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative one is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded negative zero is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded one is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded one is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN negative zero with length of padded zero is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of padded zero is zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of zero is padded zero': ['invalid'],
        'OP_NUM2BIN negative zero with length of zero is zero': [],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of negative one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of one is padded zero': ['2023_p2sh_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded one is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of padded zero is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero (520 bytes) with length of zero is zero': ['2023_p2sh_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of negative one is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of negative one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of negative zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of negative zero is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of one is padded zero': ['chip_bigint'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative one (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative one (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative one is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative zero (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative zero (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded negative zero is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded one (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded one (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded one is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded zero (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded zero (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of padded zero is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero (521 bytes) with length of zero is zero': ['chip_bigint'],
        'OP_NUM2BIN padded negative zero with length of negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of negative one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of one is padded zero': [],
        'OP_NUM2BIN padded negative zero with length of one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded one is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded one is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded negative zero with length of padded zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of padded zero is zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded negative zero with length of zero is zero': [],
        'OP_NUM2BIN padded zero (520 bytes) with length of negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of negative one is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of one is padded zero': ['2023_p2sh_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of one is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative one is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded one is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded one is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of padded zero is zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero (520 bytes) with length of zero is zero': ['2023_p2sh_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of negative one is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of negative one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of negative zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of negative zero is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of one is padded zero': ['chip_bigint'],
        'OP_NUM2BIN padded zero (521 bytes) with length of one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative one (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative one (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative one is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative zero (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative zero (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded negative zero is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded one (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded one (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded one is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded one is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded zero (520 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded zero (520 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of padded zero is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of zero is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero (521 bytes) with length of zero is zero': ['chip_bigint'],
        'OP_NUM2BIN padded zero with length of negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of negative one is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of one is padded zero': [],
        'OP_NUM2BIN padded zero with length of one is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded negative one is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative one is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded negative zero is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded one is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded one is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN padded zero with length of padded zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of padded zero is zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of zero is padded zero': ['invalid'],
        'OP_NUM2BIN padded zero with length of zero is zero': [],
        'OP_NUM2BIN zero with length of negative one is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of negative one is zero': ['invalid'],
        'OP_NUM2BIN zero with length of negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of negative zero is zero': ['invalid'],
        'OP_NUM2BIN zero with length of one is padded zero': [],
        'OP_NUM2BIN zero with length of one is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded negative one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded negative one is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative one is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded negative zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded negative zero is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded negative zero is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded one (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded one (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded one (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded one (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded one is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded one is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded zero (520 bytes) is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded zero (520 bytes) is zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded zero (521 bytes) is padded zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded zero (521 bytes) is zero': ['chip_bigint_invalid'],
        'OP_NUM2BIN zero with length of padded zero is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of padded zero is zero': ['invalid'],
        'OP_NUM2BIN zero with length of zero is padded zero': ['invalid'],
        'OP_NUM2BIN zero with length of zero is zero': [],
      }),

      ['<520>', '<0> <520> OP_NUM2BIN OP_SIZE OP_NIP OP_EQUAL', 'OP_NUM2BIN of 520 bytes'],
      ['<521>', '<0> <521> OP_NUM2BIN OP_SIZE OP_NIP OP_EQUAL', 'OP_NUM2BIN of 521 bytes', ['chip_bigint']],
      ['<10000>', '<0> <10000> OP_NUM2BIN OP_SIZE OP_NIP OP_EQUAL', 'OP_NUM2BIN of 10,000 bytes', ['chip_bigint']],
      ['<10001>', '<0> <10001> OP_NUM2BIN OP_SIZE OP_NIP OP_EQUAL', 'OP_NUM2BIN of 10,001 bytes', ['chip_bigint_invalid']],

      ['<0x1234000000000000>', '<0x1234> <8> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN retains endianness and appends padding'],
      ['<0x0012340000000000>', '<0x001234> <8> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN numbers beginning with 0x00'],
      ['<0x001234>', 'OP_DUP <8> OP_NUM2BIN OP_BIN2NUM OP_EQUAL', 'OP_NUM2BIN then OP_BIN2NUM numbers beginning with 0x00'],
      ['<0x1234000000000000>', '<0x123400> <8> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN accepts padded numbers'],
      ['<0x123400>', 'OP_DUP <8> OP_NUM2BIN OP_BIN2NUM OP_EQUAL', 'OP_NUM2BIN padded number then OP_BIN2NUM is not equal (fail)', ['invalid']],
      ['<0x123400>', 'OP_DUP <8> OP_NUM2BIN OP_BIN2NUM OP_NUMNOTEQUAL', 'OP_NUM2BIN padded number then OP_BIN2NUM, OP_NUMNOTEQUAL requires minimal encoding (fail)', ['invalid']],
      ['<0x123400>', 'OP_DUP <8> OP_NUM2BIN OP_BIN2NUM OP_EQUAL OP_NOT', 'OP_NUM2BIN padded number then OP_BIN2NUM is not equal (succeed)'],

      ['<256>', '<0> <0x0001> OP_NUM2BIN OP_SIZE OP_NIP OP_EQUAL', 'OP_NUM2BIN 0 with length of 256'],
      [`<0x1234 ${repeat('0x00', 125)}>`, '<13330> <127> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN positive integer length of 127'],
      [`<0x1234 ${repeat('0x00', 126)}>`, '<13330> <128> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN positive integer length of 128'],
      [`<0x1234 ${repeat('0x00', 518)}>`, '<13330> <520> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN positive integer length of 520'],
      [`<0x1234 ${repeat('0x00', 519)}>`, '<13330> <521> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN positive integer length of 521', ['chip_bigint']],
      [`<0x12b4>`, '<0x1234 0x80> <2> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN reduce-able negative integer'],
      [`<0x1234 ${repeat('0x00', 124)} 0x80>`, '<0x12b4> <127> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN negative integer length of 127'],
      [`<0x1234 ${repeat('0x00', 125)} 0x80>`, '<-13330> <128> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN negative integer length of 128'],
      [`<0x1234 ${repeat('0x00', 517)} 0x80>`, '<-13330> <520> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN negative integer length of 520'],
      [`<0x1234 ${repeat('0x00', 518)} 0x80>`, '<-13330> <521> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN negative integer length of 521', ['chip_bigint']],
      [`<0x00 "cash" 0x00 ${repeat('0x00', 121)}>`, '<0x00 "cash" 0x00> <127> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN padded bytes length of 127'],
      [`<0x00 "cash" 0x00 ${repeat('0x00', 122)}>`, '<0x00 "cash" 0x00> <128> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN padded bytes length of 128'],
      [`<0x00 "cash" 0x00 ${repeat('0x00', 514)}>`, '<0x00 "cash" 0x00> <520> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN padded bytes length of 520'],
      [`<0x00 "cash" 0x00 ${repeat('0x00', 515)}>`, '<0x00 "cash" 0x00> <521> OP_NUM2BIN OP_EQUAL', 'OP_NUM2BIN padded bytes length of 521', ['chip_bigint']],
    ],
  ],
] as const satisfies VmbTestDefinitionGroup[];
