import type { PossibleTestValue, VmbTestDefinitionGroup } from '../../lib.js';
import { generateTestCases, setExpectedResults } from '../bch-vmb-test-utils.js';

const signatureAlgorithms: PossibleTestValue[] = [
  ['ECDSA', 'ecdsa'],
  ['Schnorr', 'schnorr'],
];

export default [
  [
    'Signature checking',
    [
      ...setExpectedResults(
        generateTestCases(
          ['<$0> <$1.$2_signature.all_outputs>', '<1> <key1.public_key> <key2.public_key> <key3.public_key> OP_3 OP_CHECKMULTISIG', '1-of-3 $2 multisig with $0 ($1)'],
          [
            [
              ['checkBits of zero', '0'],
              ['checkBits of key 1', '0b1'],
              ['checkBits of key 2', '0b10'],
              ['checkBits of key 3', '0b100'],
            ],
            [
              ['key 1', 'key1'],
              ['key 2', 'key2'],
              ['key 3', 'key3'],
            ],
            signatureAlgorithms,
          ],
        ),
        {
          '1-of-3 ECDSA multisig with checkBits of key 1 (key 1)': ['invalid'],
          '1-of-3 ECDSA multisig with checkBits of key 1 (key 2)': ['invalid'],
          '1-of-3 ECDSA multisig with checkBits of key 1 (key 3)': ['invalid'],
          '1-of-3 ECDSA multisig with checkBits of key 2 (key 1)': ['invalid'],
          '1-of-3 ECDSA multisig with checkBits of key 2 (key 2)': ['invalid'],
          '1-of-3 ECDSA multisig with checkBits of key 2 (key 3)': ['invalid'],
          '1-of-3 ECDSA multisig with checkBits of key 3 (key 1)': ['invalid'],
          '1-of-3 ECDSA multisig with checkBits of key 3 (key 2)': ['invalid'],
          '1-of-3 ECDSA multisig with checkBits of key 3 (key 3)': ['invalid'],
          '1-of-3 ECDSA multisig with checkBits of zero (key 1)': ['nop2sh_standard'],
          '1-of-3 ECDSA multisig with checkBits of zero (key 2)': ['nop2sh_standard'],
          '1-of-3 ECDSA multisig with checkBits of zero (key 3)': ['nop2sh_standard'],
          '1-of-3 Schnorr multisig with checkBits of key 1 (key 1)': ['nop2sh_standard'],
          '1-of-3 Schnorr multisig with checkBits of key 1 (key 2)': ['invalid'],
          '1-of-3 Schnorr multisig with checkBits of key 1 (key 3)': ['invalid'],
          '1-of-3 Schnorr multisig with checkBits of key 2 (key 1)': ['invalid'],
          '1-of-3 Schnorr multisig with checkBits of key 2 (key 2)': ['nop2sh_standard'],
          '1-of-3 Schnorr multisig with checkBits of key 2 (key 3)': ['invalid'],
          '1-of-3 Schnorr multisig with checkBits of key 3 (key 1)': ['invalid'],
          '1-of-3 Schnorr multisig with checkBits of key 3 (key 2)': ['invalid'],
          '1-of-3 Schnorr multisig with checkBits of key 3 (key 3)': ['nop2sh_standard'],
          '1-of-3 Schnorr multisig with checkBits of zero (key 1)': ['invalid'],
          '1-of-3 Schnorr multisig with checkBits of zero (key 2)': ['invalid'],
          '1-of-3 Schnorr multisig with checkBits of zero (key 3)': ['invalid'],
        },
      ),
      ...setExpectedResults(
        generateTestCases(
          ['<$0> <$1.$2_signature.all_outputs> <$3.$4_signature.all_outputs>', '<2> <key1.public_key> <key2.public_key> <key3.public_key> OP_3 OP_CHECKMULTISIG', '2-of-3 multisig with $0 ($2 $1, $4 $3)'],
          [
            [
              ['checkBits of zero', '0'],
              ['checkBits of key 1', '0b1'],
              ['checkBits of key 2', '0b10'],
              ['checkBits of key 3', '0b100'],
              ['checkBits of keys 1 and 2', '0b11'],
              ['checkBits of keys 2 and 3', '0b110'],
              ['checkBits of keys 1 and 3', '0b101'],
            ],
            [
              ['key 1', 'key1'],
              ['key 2', 'key2'],
              ['key 3', 'key3'],
            ],
            signatureAlgorithms,
            [
              ['key 1', 'key1'],
              ['key 2', 'key2'],
              ['key 3', 'key3'],
            ],
            signatureAlgorithms,
          ],
        ),
        {
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 1, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 1, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 1, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 1, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 1, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 1, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 2, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 2, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 2, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 2, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 2, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 2, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 3, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 3, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 3, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 3, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 3, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (ECDSA key 3, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 1, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 1, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 1, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 1, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 1, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 1, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 2, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 2, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 2, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 2, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 2, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 2, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 3, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 3, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 3, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 3, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 3, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 1 (Schnorr key 3, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 1, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 1, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 1, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 1, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 1, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 1, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 2, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 2, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 2, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 2, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 2, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 2, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 3, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 3, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 3, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 3, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 3, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (ECDSA key 3, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 1, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 1, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 1, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 1, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 1, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 1, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 2, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 2, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 2, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 2, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 2, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 2, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 3, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 3, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 3, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 3, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 3, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 2 (Schnorr key 3, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 1, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 1, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 1, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 1, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 1, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 1, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 2, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 2, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 2, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 2, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 2, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 2, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 3, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 3, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 3, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 3, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 3, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (ECDSA key 3, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 1, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 1, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 1, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 1, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 1, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 1, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 2, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 2, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 2, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 2, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 2, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 2, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 3, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 3, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 3, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 3, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 3, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of key 3 (Schnorr key 3, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 1, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 1, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 1, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 1, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 1, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 1, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 2, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 2, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 2, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 2, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 2, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 2, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 3, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 3, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 3, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 3, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 3, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (ECDSA key 3, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 1, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 1, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 1, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 1, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 1, Schnorr key 2)': ['nop2sh_standard'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 1, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 2, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 2, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 2, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 2, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 2, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 2, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 3, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 3, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 3, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 3, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 3, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 2 (Schnorr key 3, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 1, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 1, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 1, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 1, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 1, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 1, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 2, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 2, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 2, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 2, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 2, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 2, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 3, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 3, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 3, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 3, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 3, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (ECDSA key 3, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 1, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 1, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 1, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 1, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 1, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 1, Schnorr key 3)': ['nop2sh_standard'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 2, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 2, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 2, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 2, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 2, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 2, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 3, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 3, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 3, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 3, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 3, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 1 and 3 (Schnorr key 3, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 1, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 1, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 1, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 1, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 1, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 1, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 2, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 2, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 2, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 2, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 2, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 2, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 3, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 3, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 3, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 3, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 3, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (ECDSA key 3, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 1, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 1, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 1, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 1, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 1, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 1, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 2, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 2, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 2, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 2, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 2, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 2, Schnorr key 3)': ['nop2sh_standard'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 3, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 3, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 3, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 3, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 3, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of keys 2 and 3 (Schnorr key 3, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 1, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 1, ECDSA key 2)': ['nop2sh_standard'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 1, ECDSA key 3)': ['nop2sh_standard'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 1, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 1, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 1, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 2, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 2, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 2, ECDSA key 3)': ['nop2sh_standard'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 2, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 2, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 2, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 3, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 3, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 3, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 3, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 3, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (ECDSA key 3, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 1, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 1, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 1, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 1, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 1, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 1, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 2, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 2, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 2, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 2, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 2, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 2, Schnorr key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 3, ECDSA key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 3, ECDSA key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 3, ECDSA key 3)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 3, Schnorr key 1)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 3, Schnorr key 2)': ['invalid'],
          '2-of-3 multisig with checkBits of zero (Schnorr key 3, Schnorr key 3)': ['invalid'],
        },
      ),
    ],
  ],
] as const satisfies VmbTestDefinitionGroup[];
