import type { PossibleTestValue, VmbTestDefinitionGroup } from '../../lib.js';
import { generateTestCases, setExpectedResults } from '../bch-vmb-test-utils.js';

const signatureAlgorithms: PossibleTestValue[] = [
  ['ECDSA', 'ecdsa'],
  ['Schnorr', 'schnorr'],
];

export default [
  [
    'Signature checking',
    [
      ...setExpectedResults(
        generateTestCases(
          [
            '<$0> <$2.$1_signature.all_outputs> <$3.$1_signature.all_outputs>',
            '<2> <key1.public_key> <key2.public_key> <key3.public_key> <key4.public_key> <key5.public_key> <key6.public_key> <key7.public_key> <key8.public_key> <key9.public_key> <key10.public_key> <key11.public_key> <key12.public_key> <key13.public_key> <key14.public_key> <key15.public_key> <key16.public_key> <key17.public_key> <key18.public_key> <key19.public_key> <key20.public_key> <20> OP_CHECKMULTISIG',
            '2-of-20 multisig with $0 ($1, $2 and $3)',
          ],
          [
            [
              ['checkBits of zero', '0'],
              ['checkBits of keys 1 and 13', '0b00000001 0b00010000 0b00000000'],
              ['checkBits of keys 1 and 20', '0b00000001 0b00000000 0b00001000'],
              ['checkBits of keys 13 and 20', '0b00000000 0b00010000 0b00001000'],
            ],
            signatureAlgorithms,
            [
              ['key 1', 'key1'],
              ['key 13', 'key13'],
              ['key 20', 'key20'],
            ],
            [
              ['key 1', 'key1'],
              ['key 13', 'key13'],
              ['key 20', 'key20'],
            ],
          ],
        ),
        {
          '2-of-20 multisig with checkBits of keys 1 and 13 (ECDSA, key 1 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (ECDSA, key 1 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (ECDSA, key 1 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (ECDSA, key 13 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (ECDSA, key 13 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (ECDSA, key 13 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (ECDSA, key 20 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (ECDSA, key 20 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (ECDSA, key 20 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (Schnorr, key 1 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (Schnorr, key 1 and key 13)': ['2023_p2sh_invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (Schnorr, key 1 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (Schnorr, key 13 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (Schnorr, key 13 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (Schnorr, key 13 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (Schnorr, key 20 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (Schnorr, key 20 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 13 (Schnorr, key 20 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (ECDSA, key 1 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (ECDSA, key 1 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (ECDSA, key 1 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (ECDSA, key 13 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (ECDSA, key 13 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (ECDSA, key 13 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (ECDSA, key 20 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (ECDSA, key 20 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (ECDSA, key 20 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (Schnorr, key 1 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (Schnorr, key 1 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (Schnorr, key 1 and key 20)': ['2023_p2sh_invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (Schnorr, key 13 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (Schnorr, key 13 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (Schnorr, key 13 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (Schnorr, key 20 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (Schnorr, key 20 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 1 and 20 (Schnorr, key 20 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (ECDSA, key 1 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (ECDSA, key 1 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (ECDSA, key 1 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (ECDSA, key 13 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (ECDSA, key 13 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (ECDSA, key 13 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (ECDSA, key 20 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (ECDSA, key 20 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (ECDSA, key 20 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (Schnorr, key 1 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (Schnorr, key 1 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (Schnorr, key 1 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (Schnorr, key 13 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (Schnorr, key 13 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (Schnorr, key 13 and key 20)': ['2023_p2sh_invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (Schnorr, key 20 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (Schnorr, key 20 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of keys 13 and 20 (Schnorr, key 20 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of zero (ECDSA, key 1 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of zero (ECDSA, key 1 and key 13)': ['nop2sh_invalid', '2023_p2sh_invalid'],
          '2-of-20 multisig with checkBits of zero (ECDSA, key 1 and key 20)': ['nop2sh_invalid', '2023_p2sh_invalid'],
          '2-of-20 multisig with checkBits of zero (ECDSA, key 13 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of zero (ECDSA, key 13 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of zero (ECDSA, key 13 and key 20)': ['nop2sh_invalid', '2023_p2sh_invalid'],
          '2-of-20 multisig with checkBits of zero (ECDSA, key 20 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of zero (ECDSA, key 20 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of zero (ECDSA, key 20 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of zero (Schnorr, key 1 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of zero (Schnorr, key 1 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of zero (Schnorr, key 1 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of zero (Schnorr, key 13 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of zero (Schnorr, key 13 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of zero (Schnorr, key 13 and key 20)': ['invalid'],
          '2-of-20 multisig with checkBits of zero (Schnorr, key 20 and key 1)': ['invalid'],
          '2-of-20 multisig with checkBits of zero (Schnorr, key 20 and key 13)': ['invalid'],
          '2-of-20 multisig with checkBits of zero (Schnorr, key 20 and key 20)': ['invalid'],
        },
      ),

      ...setExpectedResults(
        generateTestCases(
          [
            '<$0> <key1.$1_signature.all_outputs> <key2.$1_signature.all_outputs> <key3.$1_signature.all_outputs> <key4.$1_signature.all_outputs> <key5.$1_signature.all_outputs> <key6.$1_signature.all_outputs> <key7.$1_signature.all_outputs> <key8.$1_signature.all_outputs>',
            '<8> <key1.public_key> <key2.public_key> <key3.public_key> <key4.public_key> <key5.public_key> <key6.public_key> <key7.public_key> <key8.public_key> <key9.public_key> <key10.public_key> <key11.public_key> <key12.public_key> <key13.public_key> <key14.public_key> <key15.public_key> <key16.public_key> <key17.public_key> <key18.public_key> <key19.public_key> <key20.public_key> <20> OP_CHECKMULTISIG',
            '8-of-20 $1 multisig with $0 (keys 1 to 8)',
          ],
          [
            [
              ['checkBits of zero', '0'],
              ['one-byte checkBits of keys 1 to 8', '0b11111111'],
              ['checkBits of keys 1 to 8', '0b11111111 0b00000000 0b00000000'],
            ],
            signatureAlgorithms,
          ],
        ),
        {
          '8-of-20 ECDSA multisig with checkBits of keys 1 to 8 (keys 1 to 8)': ['invalid'],
          /* */
          '8-of-20 ECDSA multisig with checkBits of zero (keys 1 to 8)': ['nop2sh_invalid', '2023_p2sh_invalid'],
          '8-of-20 ECDSA multisig with one-byte checkBits of keys 1 to 8 (keys 1 to 8)': ['invalid'],
          '8-of-20 Schnorr multisig with checkBits of keys 1 to 8 (keys 1 to 8)': ['2023_p2sh_invalid'],
          '8-of-20 Schnorr multisig with checkBits of zero (keys 1 to 8)': ['invalid'],
          '8-of-20 Schnorr multisig with one-byte checkBits of keys 1 to 8 (keys 1 to 8)': ['invalid'],
        },
      ),
      ...setExpectedResults(
        generateTestCases(
          [
            '<$0> <key1.$1_signature.all_outputs> <key2.$1_signature.all_outputs> <key3.$1_signature.all_outputs> <key4.$1_signature.all_outputs> <key5.$1_signature.all_outputs> <key6.$1_signature.all_outputs> <key7.$1_signature.all_outputs> <key8.$1_signature.all_outputs> <key9.$1_signature.all_outputs>',
            '<9> <key1.public_key> <key2.public_key> <key3.public_key> <key4.public_key> <key5.public_key> <key6.public_key> <key7.public_key> <key8.public_key> <key9.public_key> <key10.public_key> <key11.public_key> <key12.public_key> <key13.public_key> <key14.public_key> <key15.public_key> <key16.public_key> <key17.public_key> <key18.public_key> <key19.public_key> <key20.public_key> <20> OP_CHECKMULTISIG',
            '9-of-20 $1 multisig with $0 (keys 1 to 9)',
          ],
          [
            [
              ['checkBits of zero', '0'],
              ['checkBits of keys 1 to 9', '0b11111111 0b00000001 0b00000000'],
            ],
            signatureAlgorithms,
          ],
        ),
        {
          '9-of-20 ECDSA multisig with checkBits of keys 1 to 9 (keys 1 to 9)': ['invalid'],
          '9-of-20 ECDSA multisig with checkBits of zero (keys 1 to 9)': ['2023_p2sh_invalid'],
          '9-of-20 Schnorr multisig with checkBits of keys 1 to 9 (keys 1 to 9)': ['2023_p2sh_invalid'],
          '9-of-20 Schnorr multisig with checkBits of zero (keys 1 to 9)': ['invalid'],
        },
      ),

      ...setExpectedResults(
        generateTestCases(
          ['<$0> <$2.$1_signature.all_outputs> <key3.$1_signature.all_outputs>', '<2> <$3> OP_DUP OP_DUP OP_DUP OP_DUP OP_DUP OP_DUP OP_DUP OP_DUP OP_DUP OP_DUP OP_DUP OP_DUP OP_DUP <key2.public_key> OP_OVER OP_DUP OP_DUP OP_DUP <key3.public_key> <20> OP_CHECKMULTISIG', '2-of-20 $1 multisig with $0, signatures $2 and 20, and $3'],
          [
            [
              ['checkBits of zero', '0'],
              ['checkBits of keys 15 and 20', '0b00000000 0b01000000 0b00001000'],
              ['checkBits of keys 19 and 20', '0b00000000 0b00000000 0b00001100'],
            ],
            signatureAlgorithms,
            [
              ['15', 'key2'],
              ['19', 'key1'],
            ],
            [
              ['valid public key 19', 'key1.public_key'],
              ['invalid public key 19', '0'],
            ],
          ],
        ),
        {
          '2-of-20 ECDSA multisig with checkBits of keys 15 and 20, signatures 15 and 20, and invalid public key 19': ['invalid'],
          '2-of-20 ECDSA multisig with checkBits of keys 15 and 20, signatures 15 and 20, and valid public key 19': ['invalid'],
          '2-of-20 ECDSA multisig with checkBits of keys 15 and 20, signatures 19 and 20, and invalid public key 19': ['invalid'],
          '2-of-20 ECDSA multisig with checkBits of keys 15 and 20, signatures 19 and 20, and valid public key 19': ['invalid'],
          '2-of-20 ECDSA multisig with checkBits of keys 19 and 20, signatures 15 and 20, and invalid public key 19': ['invalid'],
          '2-of-20 ECDSA multisig with checkBits of keys 19 and 20, signatures 15 and 20, and valid public key 19': ['invalid'],
          '2-of-20 ECDSA multisig with checkBits of keys 19 and 20, signatures 19 and 20, and invalid public key 19': ['invalid'],
          '2-of-20 ECDSA multisig with checkBits of keys 19 and 20, signatures 19 and 20, and valid public key 19': ['invalid'],
          '2-of-20 ECDSA multisig with checkBits of zero, signatures 15 and 20, and invalid public key 19': ['invalid'],
          '2-of-20 ECDSA multisig with checkBits of zero, signatures 15 and 20, and valid public key 19': ['invalid', '2023_nonstandard'],
          '2-of-20 ECDSA multisig with checkBits of zero, signatures 19 and 20, and invalid public key 19': ['invalid'],
          '2-of-20 ECDSA multisig with checkBits of zero, signatures 19 and 20, and valid public key 19': ['invalid', '2023_nonstandard'],
          '2-of-20 Schnorr multisig with checkBits of keys 15 and 20, signatures 15 and 20, and invalid public key 19': [],
          '2-of-20 Schnorr multisig with checkBits of keys 15 and 20, signatures 15 and 20, and valid public key 19': [],
          '2-of-20 Schnorr multisig with checkBits of keys 15 and 20, signatures 19 and 20, and invalid public key 19': ['invalid'],
          '2-of-20 Schnorr multisig with checkBits of keys 15 and 20, signatures 19 and 20, and valid public key 19': ['invalid'],
          '2-of-20 Schnorr multisig with checkBits of keys 19 and 20, signatures 15 and 20, and invalid public key 19': ['invalid'],
          '2-of-20 Schnorr multisig with checkBits of keys 19 and 20, signatures 15 and 20, and valid public key 19': ['invalid'],
          '2-of-20 Schnorr multisig with checkBits of keys 19 and 20, signatures 19 and 20, and invalid public key 19': ['invalid'],
          '2-of-20 Schnorr multisig with checkBits of keys 19 and 20, signatures 19 and 20, and valid public key 19': [],
          '2-of-20 Schnorr multisig with checkBits of zero, signatures 15 and 20, and invalid public key 19': ['invalid'],
          '2-of-20 Schnorr multisig with checkBits of zero, signatures 15 and 20, and valid public key 19': ['invalid'],
          '2-of-20 Schnorr multisig with checkBits of zero, signatures 19 and 20, and invalid public key 19': ['invalid'],
          '2-of-20 Schnorr multisig with checkBits of zero, signatures 19 and 20, and valid public key 19': ['invalid'],
        },
      ),
    ],
  ],
] as const satisfies VmbTestDefinitionGroup[];
