import type { VmbTestDefinitionGroup } from '../../lib.js';
import { divTests } from '../bch-vmb-test-mixins.bigint.js';
import { mapTestCases, setExpectedResults } from '../bch-vmb-test-utils.js';

export default [
  [
    'BigInt',
    [
      ...setExpectedResults(mapTestCases(['<$2>', '<$0> <$1> OP_DIV OP_EQUAL', 'OP_DIV $0 and $1'], divTests, { prefixAsHexLiterals: true }), {
        'OP_DIV 1-byte number (all bits set) and 1-byte number (all bits set)': [],
        'OP_DIV 1-byte number (all bits set) and 4096-byte number (all bits set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 1-byte number (all bits set) and 512-byte number (all bits set)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 1-byte number (all bits set) and 64-byte number (all bits set)': ['2023_invalid'],
        'OP_DIV 1-byte number (all bits set) and 8-byte number (all bits set)': [],
        'OP_DIV 1-byte number (all bits set) and 8192-byte number (all bits set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 1-byte number (alternating bits set) and 1-byte number (alternating bits set)': [],
        'OP_DIV 1-byte number (alternating bits set) and 4096-byte number (alternating bits set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 1-byte number (alternating bits set) and 512-byte number (alternating bits set)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 1-byte number (alternating bits set) and 64-byte number (alternating bits set)': ['2023_invalid'],
        'OP_DIV 1-byte number (alternating bits set) and 8-byte number (alternating bits set)': [],
        'OP_DIV 1-byte number (alternating bits set) and 8192-byte number (alternating bits set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 1-byte number (highest-bit set) and 1-byte number (highest-bit set)': [],
        'OP_DIV 1-byte number (highest-bit set) and 4096-byte number (highest-bit set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 1-byte number (highest-bit set) and 512-byte number (highest-bit set)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 1-byte number (highest-bit set) and 64-byte number (highest-bit set)': ['2023_invalid'],
        'OP_DIV 1-byte number (highest-bit set) and 8-byte number (highest-bit set)': [],
        'OP_DIV 1-byte number (highest-bit set) and 8192-byte number (highest-bit set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 1-byte number (one bit set per byte) and 1-byte number (one bit set per byte)': ['skip'],
        'OP_DIV 1-byte number (one bit set per byte) and 4096-byte number (one bit set per byte)': ['skip'],
        'OP_DIV 1-byte number (one bit set per byte) and 512-byte number (one bit set per byte)': ['skip'],
        'OP_DIV 1-byte number (one bit set per byte) and 64-byte number (one bit set per byte)': ['skip'],
        'OP_DIV 1-byte number (one bit set per byte) and 8-byte number (one bit set per byte)': ['skip'],
        'OP_DIV 1-byte number (one bit set per byte) and 8192-byte number (one bit set per byte)': ['skip'],
        'OP_DIV 4096-byte number (all bits set) and 1-byte number (all bits set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (all bits set) and 4096-byte number (all bits set)': ['invalid'],
        'OP_DIV 4096-byte number (all bits set) and 512-byte number (all bits set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (all bits set) and 64-byte number (all bits set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (all bits set) and 8-byte number (all bits set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (all bits set) and 8192-byte number (all bits set)': ['invalid'],
        'OP_DIV 4096-byte number (alternating bits set) and 1-byte number (alternating bits set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (alternating bits set) and 4096-byte number (alternating bits set)': ['invalid'],
        'OP_DIV 4096-byte number (alternating bits set) and 512-byte number (alternating bits set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (alternating bits set) and 64-byte number (alternating bits set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (alternating bits set) and 8-byte number (alternating bits set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (alternating bits set) and 8192-byte number (alternating bits set)': ['invalid'],
        'OP_DIV 4096-byte number (highest-bit set) and 1-byte number (highest-bit set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (highest-bit set) and 4096-byte number (highest-bit set)': ['invalid'],
        'OP_DIV 4096-byte number (highest-bit set) and 512-byte number (highest-bit set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (highest-bit set) and 64-byte number (highest-bit set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (highest-bit set) and 8-byte number (highest-bit set)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (highest-bit set) and 8192-byte number (highest-bit set)': ['invalid'],
        'OP_DIV 4096-byte number (one bit set per byte) and 1-byte number (one bit set per byte)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (one bit set per byte) and 4096-byte number (one bit set per byte)': ['invalid'],
        'OP_DIV 4096-byte number (one bit set per byte) and 512-byte number (one bit set per byte)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (one bit set per byte) and 64-byte number (one bit set per byte)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (one bit set per byte) and 8-byte number (one bit set per byte)': ['p2s_nonstandard', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 4096-byte number (one bit set per byte) and 8192-byte number (one bit set per byte)': ['invalid'],
        'OP_DIV 512-byte number (all bits set) and 1-byte number (all bits set)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 512-byte number (all bits set) and 4096-byte number (all bits set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 512-byte number (all bits set) and 512-byte number (all bits set)': ['p2s_invalid', '2023_invalid'],
        'OP_DIV 512-byte number (all bits set) and 64-byte number (all bits set)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 512-byte number (all bits set) and 8-byte number (all bits set)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 512-byte number (all bits set) and 8192-byte number (all bits set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 512-byte number (alternating bits set) and 1-byte number (alternating bits set)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 512-byte number (alternating bits set) and 4096-byte number (alternating bits set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 512-byte number (alternating bits set) and 512-byte number (alternating bits set)': ['p2s_invalid', '2023_invalid'],
        'OP_DIV 512-byte number (alternating bits set) and 64-byte number (alternating bits set)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 512-byte number (alternating bits set) and 8-byte number (alternating bits set)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 512-byte number (alternating bits set) and 8192-byte number (alternating bits set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 512-byte number (highest-bit set) and 1-byte number (highest-bit set)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 512-byte number (highest-bit set) and 4096-byte number (highest-bit set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 512-byte number (highest-bit set) and 512-byte number (highest-bit set)': ['p2s_invalid', '2023_invalid'],
        'OP_DIV 512-byte number (highest-bit set) and 64-byte number (highest-bit set)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 512-byte number (highest-bit set) and 8-byte number (highest-bit set)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 512-byte number (highest-bit set) and 8192-byte number (highest-bit set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 512-byte number (one bit set per byte) and 1-byte number (one bit set per byte)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 512-byte number (one bit set per byte) and 4096-byte number (one bit set per byte)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 512-byte number (one bit set per byte) and 512-byte number (one bit set per byte)': ['p2s_invalid', '2023_invalid'],
        'OP_DIV 512-byte number (one bit set per byte) and 64-byte number (one bit set per byte)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 512-byte number (one bit set per byte) and 8-byte number (one bit set per byte)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 512-byte number (one bit set per byte) and 8192-byte number (one bit set per byte)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 64-byte number (all bits set) and 1-byte number (all bits set)': ['2023_invalid'],
        'OP_DIV 64-byte number (all bits set) and 4096-byte number (all bits set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 64-byte number (all bits set) and 512-byte number (all bits set)': ['p2s_invalid', '2023_invalid'],
        'OP_DIV 64-byte number (all bits set) and 64-byte number (all bits set)': ['2023_invalid'],
        'OP_DIV 64-byte number (all bits set) and 8-byte number (all bits set)': ['2023_invalid'],
        'OP_DIV 64-byte number (all bits set) and 8192-byte number (all bits set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 64-byte number (alternating bits set) and 1-byte number (alternating bits set)': ['2023_invalid'],
        'OP_DIV 64-byte number (alternating bits set) and 4096-byte number (alternating bits set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 64-byte number (alternating bits set) and 512-byte number (alternating bits set)': ['p2s_invalid', '2023_invalid'],
        'OP_DIV 64-byte number (alternating bits set) and 64-byte number (alternating bits set)': ['2023_invalid'],
        'OP_DIV 64-byte number (alternating bits set) and 8-byte number (alternating bits set)': ['2023_invalid'],
        'OP_DIV 64-byte number (alternating bits set) and 8192-byte number (alternating bits set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 64-byte number (highest-bit set) and 1-byte number (highest-bit set)': ['2023_invalid'],
        'OP_DIV 64-byte number (highest-bit set) and 4096-byte number (highest-bit set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 64-byte number (highest-bit set) and 512-byte number (highest-bit set)': ['p2s_invalid', '2023_invalid'],
        'OP_DIV 64-byte number (highest-bit set) and 64-byte number (highest-bit set)': ['2023_invalid'],
        'OP_DIV 64-byte number (highest-bit set) and 8-byte number (highest-bit set)': ['2023_invalid'],
        'OP_DIV 64-byte number (highest-bit set) and 8192-byte number (highest-bit set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 64-byte number (one bit set per byte) and 1-byte number (one bit set per byte)': ['2023_invalid'],
        'OP_DIV 64-byte number (one bit set per byte) and 4096-byte number (one bit set per byte)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 64-byte number (one bit set per byte) and 512-byte number (one bit set per byte)': ['p2s_invalid', '2023_invalid'],
        'OP_DIV 64-byte number (one bit set per byte) and 64-byte number (one bit set per byte)': ['2023_invalid'],
        'OP_DIV 64-byte number (one bit set per byte) and 8-byte number (one bit set per byte)': ['2023_invalid'],
        'OP_DIV 64-byte number (one bit set per byte) and 8192-byte number (one bit set per byte)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 8-byte number (all bits set) and 1-byte number (all bits set)': [],
        'OP_DIV 8-byte number (all bits set) and 4096-byte number (all bits set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 8-byte number (all bits set) and 512-byte number (all bits set)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 8-byte number (all bits set) and 64-byte number (all bits set)': ['2023_invalid'],
        'OP_DIV 8-byte number (all bits set) and 8-byte number (all bits set)': [],
        'OP_DIV 8-byte number (all bits set) and 8192-byte number (all bits set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 8-byte number (alternating bits set) and 1-byte number (alternating bits set)': [],
        'OP_DIV 8-byte number (alternating bits set) and 4096-byte number (alternating bits set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 8-byte number (alternating bits set) and 512-byte number (alternating bits set)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 8-byte number (alternating bits set) and 64-byte number (alternating bits set)': ['2023_invalid'],
        'OP_DIV 8-byte number (alternating bits set) and 8-byte number (alternating bits set)': [],
        'OP_DIV 8-byte number (alternating bits set) and 8192-byte number (alternating bits set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 8-byte number (highest-bit set) and 1-byte number (highest-bit set)': [],
        'OP_DIV 8-byte number (highest-bit set) and 4096-byte number (highest-bit set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 8-byte number (highest-bit set) and 512-byte number (highest-bit set)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 8-byte number (highest-bit set) and 64-byte number (highest-bit set)': ['2023_invalid'],
        'OP_DIV 8-byte number (highest-bit set) and 8-byte number (highest-bit set)': [],
        'OP_DIV 8-byte number (highest-bit set) and 8192-byte number (highest-bit set)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 8-byte number (one bit set per byte) and 1-byte number (one bit set per byte)': [],
        'OP_DIV 8-byte number (one bit set per byte) and 4096-byte number (one bit set per byte)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 8-byte number (one bit set per byte) and 512-byte number (one bit set per byte)': ['p2s_nonstandard', '2023_invalid'],
        'OP_DIV 8-byte number (one bit set per byte) and 64-byte number (one bit set per byte)': ['2023_invalid'],
        'OP_DIV 8-byte number (one bit set per byte) and 8-byte number (one bit set per byte)': [],
        'OP_DIV 8-byte number (one bit set per byte) and 8192-byte number (one bit set per byte)': ['p2s_invalid', '2023_invalid', '2025_p2sh_nonstandard'],
        'OP_DIV 8192-byte number (all bits set) and 1-byte number (all bits set)': ['nonstandard', '2023_invalid', 'p2sh_ignore'],
        'OP_DIV 8192-byte number (all bits set) and 4096-byte number (all bits set)': ['invalid'],
        'OP_DIV 8192-byte number (all bits set) and 512-byte number (all bits set)': ['nonstandard', '2023_invalid', 'p2sh_ignore'],
        'OP_DIV 8192-byte number (all bits set) and 64-byte number (all bits set)': ['nonstandard', '2023_invalid', 'p2sh_ignore'],
        'OP_DIV 8192-byte number (all bits set) and 8-byte number (all bits set)': ['nonstandard', '2023_invalid', 'p2sh_ignore'],
        'OP_DIV 8192-byte number (all bits set) and 8192-byte number (all bits set)': ['invalid'],
        'OP_DIV 8192-byte number (alternating bits set) and 1-byte number (alternating bits set)': ['nonstandard', 'p2sh_invalid', '2023_invalid'],
        'OP_DIV 8192-byte number (alternating bits set) and 4096-byte number (alternating bits set)': ['invalid'],
        'OP_DIV 8192-byte number (alternating bits set) and 512-byte number (alternating bits set)': ['nonstandard', 'p2sh_invalid', '2023_invalid'],
        'OP_DIV 8192-byte number (alternating bits set) and 64-byte number (alternating bits set)': ['nonstandard', 'p2sh_invalid', '2023_invalid'],
        'OP_DIV 8192-byte number (alternating bits set) and 8-byte number (alternating bits set)': ['nonstandard', 'p2sh_invalid', '2023_invalid'],
        'OP_DIV 8192-byte number (alternating bits set) and 8192-byte number (alternating bits set)': ['invalid'],
        'OP_DIV 8192-byte number (highest-bit set) and 1-byte number (highest-bit set)': ['nonstandard', 'p2sh_invalid', '2023_invalid'],
        'OP_DIV 8192-byte number (highest-bit set) and 4096-byte number (highest-bit set)': ['invalid'],
        'OP_DIV 8192-byte number (highest-bit set) and 512-byte number (highest-bit set)': ['nonstandard', 'p2sh_invalid', '2023_invalid'],
        'OP_DIV 8192-byte number (highest-bit set) and 64-byte number (highest-bit set)': ['nonstandard', 'p2sh_invalid', '2023_invalid'],
        'OP_DIV 8192-byte number (highest-bit set) and 8-byte number (highest-bit set)': ['nonstandard', 'p2sh_invalid', '2023_invalid'],
        'OP_DIV 8192-byte number (highest-bit set) and 8192-byte number (highest-bit set)': ['invalid'],
        'OP_DIV 8192-byte number (one bit set per byte) and 1-byte number (one bit set per byte)': ['nonstandard', 'p2sh_invalid', '2023_invalid'],
        'OP_DIV 8192-byte number (one bit set per byte) and 4096-byte number (one bit set per byte)': ['invalid'],
        'OP_DIV 8192-byte number (one bit set per byte) and 512-byte number (one bit set per byte)': ['nonstandard', 'p2sh_invalid', '2023_invalid'],
        'OP_DIV 8192-byte number (one bit set per byte) and 64-byte number (one bit set per byte)': ['nonstandard', 'p2sh_invalid', '2023_invalid'],
        'OP_DIV 8192-byte number (one bit set per byte) and 8-byte number (one bit set per byte)': ['nonstandard', 'p2sh_invalid', '2023_invalid'],
        'OP_DIV 8192-byte number (one bit set per byte) and 8192-byte number (one bit set per byte)': ['invalid'],
      }),
    ],
  ],
] as const satisfies VmbTestDefinitionGroup[];
