import type { PossibleTestValue, VmbTestDefinitionGroup } from '../../lib.js';
import { generateTestCases, setExpectedResults } from '../bch-vmb-test-utils.js';

const disabledOps: PossibleTestValue[] = [
  ['OP_RESERVED', 'OP_RESERVED'],
  ['OP_VER', 'OP_VER'],
  ['OP_VERIF', 'OP_VERIF'],
  ['OP_VERNOTIF', 'OP_VERNOTIF'],
  ['OP_RETURN', 'OP_RETURN'],
  ['OP_INVERT', 'OP_INVERT'],
  ['OP_RESERVED1', 'OP_RESERVED1'],
  ['OP_RESERVED2', 'OP_RESERVED2'],
  ['OP_2MUL', 'OP_2MUL'],
  ['OP_2DIV', 'OP_2DIV'],
  ['OP_LSHIFT', 'OP_LSHIFT'],
  ['OP_RSHIFT', 'OP_RSHIFT'],
];

const unknownOps: PossibleTestValue[] = [
  ['OP_UNKNOWN189', 'OP_UNKNOWN189'],
  ['OP_UNKNOWN190', 'OP_UNKNOWN190'],
  ['OP_UNKNOWN191', 'OP_UNKNOWN191'],
  ['OP_UNKNOWN212', 'OP_UNKNOWN212'],
  ['OP_UNKNOWN213', 'OP_UNKNOWN213'],
  ['OP_UNKNOWN214', 'OP_UNKNOWN214'],
  ['OP_UNKNOWN215', 'OP_UNKNOWN215'],
  ['OP_UNKNOWN216', 'OP_UNKNOWN216'],
  ['OP_UNKNOWN217', 'OP_UNKNOWN217'],
  ['OP_UNKNOWN218', 'OP_UNKNOWN218'],
  ['OP_UNKNOWN219', 'OP_UNKNOWN219'],
  ['OP_UNKNOWN220', 'OP_UNKNOWN220'],
  ['OP_UNKNOWN221', 'OP_UNKNOWN221'],
  ['OP_UNKNOWN222', 'OP_UNKNOWN222'],
  ['OP_UNKNOWN223', 'OP_UNKNOWN223'],
  ['OP_UNKNOWN224', 'OP_UNKNOWN224'],
  ['OP_UNKNOWN225', 'OP_UNKNOWN225'],
  ['OP_UNKNOWN226', 'OP_UNKNOWN226'],
  ['OP_UNKNOWN227', 'OP_UNKNOWN227'],
  ['OP_UNKNOWN228', 'OP_UNKNOWN228'],
  ['OP_UNKNOWN229', 'OP_UNKNOWN229'],
  ['OP_UNKNOWN230', 'OP_UNKNOWN230'],
  ['OP_UNKNOWN231', 'OP_UNKNOWN231'],
  ['OP_UNKNOWN232', 'OP_UNKNOWN232'],
  ['OP_UNKNOWN233', 'OP_UNKNOWN233'],
  ['OP_UNKNOWN234', 'OP_UNKNOWN234'],
  ['OP_UNKNOWN235', 'OP_UNKNOWN235'],
  ['OP_UNKNOWN236', 'OP_UNKNOWN236'],
  ['OP_UNKNOWN237', 'OP_UNKNOWN237'],
  ['OP_UNKNOWN238', 'OP_UNKNOWN238'],
  ['OP_UNKNOWN239', 'OP_UNKNOWN239'],
  ['OP_UNKNOWN240', 'OP_UNKNOWN240'],
  ['OP_UNKNOWN241', 'OP_UNKNOWN241'],
  ['OP_UNKNOWN242', 'OP_UNKNOWN242'],
  ['OP_UNKNOWN243', 'OP_UNKNOWN243'],
  ['OP_UNKNOWN244', 'OP_UNKNOWN244'],
  ['OP_UNKNOWN245', 'OP_UNKNOWN245'],
  ['OP_UNKNOWN246', 'OP_UNKNOWN246'],
  ['OP_UNKNOWN247', 'OP_UNKNOWN247'],
  ['OP_UNKNOWN248', 'OP_UNKNOWN248'],
  ['OP_UNKNOWN249', 'OP_UNKNOWN249'],
  ['OP_UNKNOWN250', 'OP_UNKNOWN250'],
  ['OP_UNKNOWN251', 'OP_UNKNOWN251'],
  ['OP_UNKNOWN252', 'OP_UNKNOWN252'],
  ['OP_UNKNOWN253', 'OP_UNKNOWN253'],
  ['OP_UNKNOWN254', 'OP_UNKNOWN254'],
  ['OP_UNKNOWN255', 'OP_UNKNOWN255'],
];

export default [
  [
    'Disabled operations',
    [
      ...setExpectedResults(generateTestCases(['<1>', '$0', '$0 in locking bytecode'], [disabledOps]), {
        'OP_2DIV in locking bytecode': ['invalid'],
        'OP_2MUL in locking bytecode': ['invalid'],
        'OP_INVERT in locking bytecode': ['invalid'],
        'OP_LSHIFT in locking bytecode': ['invalid'],
        'OP_RESERVED in locking bytecode': ['invalid'],
        'OP_RESERVED1 in locking bytecode': ['invalid'],
        'OP_RESERVED2 in locking bytecode': ['invalid'],
        'OP_RETURN in locking bytecode': ['invalid'],
        'OP_RSHIFT in locking bytecode': ['invalid'],
        'OP_VER in locking bytecode': ['invalid'],
        'OP_VERIF in locking bytecode': ['invalid'],
        'OP_VERNOTIF in locking bytecode': ['invalid'],
      }),
      ...setExpectedResults(generateTestCases(['$0', '<1>', '$0 in unlocking bytecode'], [disabledOps]), {
        'OP_2DIV in unlocking bytecode': ['invalid'],
        'OP_2MUL in unlocking bytecode': ['invalid'],
        'OP_INVERT in unlocking bytecode': ['invalid'],
        'OP_LSHIFT in unlocking bytecode': ['invalid'],
        'OP_RESERVED in unlocking bytecode': ['invalid'],
        'OP_RESERVED1 in unlocking bytecode': ['invalid'],
        'OP_RESERVED2 in unlocking bytecode': ['invalid'],
        'OP_RETURN in unlocking bytecode': ['invalid'],
        'OP_RSHIFT in unlocking bytecode': ['invalid'],
        'OP_VER in unlocking bytecode': ['invalid'],
        'OP_VERIF in unlocking bytecode': ['invalid'],
        'OP_VERNOTIF in unlocking bytecode': ['invalid'],
      }),

      ...setExpectedResults(generateTestCases(['<0>', 'OP_IF $0 OP_ENDIF <1>', 'Unexecuted $0 in locking bytecode'], [disabledOps]), {
        'Unexecuted OP_2DIV in locking bytecode': ['invalid'],
        'Unexecuted OP_2MUL in locking bytecode': ['invalid'],
        'Unexecuted OP_INVERT in locking bytecode': ['invalid'],
        'Unexecuted OP_LSHIFT in locking bytecode': ['invalid'],
        'Unexecuted OP_RESERVED in locking bytecode': [],
        'Unexecuted OP_RESERVED1 in locking bytecode': [],
        'Unexecuted OP_RESERVED2 in locking bytecode': [],
        'Unexecuted OP_RETURN in locking bytecode': [],
        'Unexecuted OP_RSHIFT in locking bytecode': ['invalid'],
        'Unexecuted OP_VER in locking bytecode': [],
        'Unexecuted OP_VERIF in locking bytecode': ['invalid'],
        'Unexecuted OP_VERNOTIF in locking bytecode': ['invalid'],
      }),
      ...setExpectedResults(generateTestCases(['<0> OP_IF $0 OP_ENDIF', '<1>', 'Unexecuted $0 in unlocking bytecode'], [disabledOps]), {
        'Unexecuted OP_2DIV in unlocking bytecode': ['invalid'],
        'Unexecuted OP_2MUL in unlocking bytecode': ['invalid'],
        'Unexecuted OP_INVERT in unlocking bytecode': ['invalid'],
        'Unexecuted OP_LSHIFT in unlocking bytecode': ['invalid'],
        'Unexecuted OP_RESERVED in unlocking bytecode': ['invalid'],
        'Unexecuted OP_RESERVED1 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_RESERVED2 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_RETURN in unlocking bytecode': ['invalid'],
        'Unexecuted OP_RSHIFT in unlocking bytecode': ['invalid'],
        'Unexecuted OP_VER in unlocking bytecode': ['invalid'],
        'Unexecuted OP_VERIF in unlocking bytecode': ['invalid'],
        'Unexecuted OP_VERNOTIF in unlocking bytecode': ['invalid'],
      }),
    ],
  ],
  [
    'Unknown operations',
    [
      ...setExpectedResults(generateTestCases(['<1>', '$0', '$0 in locking bytecode'], [unknownOps]), {
        'OP_UNKNOWN189 in locking bytecode': ['invalid'],
        'OP_UNKNOWN190 in locking bytecode': ['invalid'],
        'OP_UNKNOWN191 in locking bytecode': ['invalid'],
        'OP_UNKNOWN212 in locking bytecode': ['invalid'],
        'OP_UNKNOWN213 in locking bytecode': ['invalid'],
        'OP_UNKNOWN214 in locking bytecode': ['invalid'],
        'OP_UNKNOWN215 in locking bytecode': ['invalid'],
        'OP_UNKNOWN216 in locking bytecode': ['invalid'],
        'OP_UNKNOWN217 in locking bytecode': ['invalid'],
        'OP_UNKNOWN218 in locking bytecode': ['invalid'],
        'OP_UNKNOWN219 in locking bytecode': ['invalid'],
        'OP_UNKNOWN220 in locking bytecode': ['invalid'],
        'OP_UNKNOWN221 in locking bytecode': ['invalid'],
        'OP_UNKNOWN222 in locking bytecode': ['invalid'],
        'OP_UNKNOWN223 in locking bytecode': ['invalid'],
        'OP_UNKNOWN224 in locking bytecode': ['invalid'],
        'OP_UNKNOWN225 in locking bytecode': ['invalid'],
        'OP_UNKNOWN226 in locking bytecode': ['invalid'],
        'OP_UNKNOWN227 in locking bytecode': ['invalid'],
        'OP_UNKNOWN228 in locking bytecode': ['invalid'],
        'OP_UNKNOWN229 in locking bytecode': ['invalid'],
        'OP_UNKNOWN230 in locking bytecode': ['invalid'],
        'OP_UNKNOWN231 in locking bytecode': ['invalid'],
        'OP_UNKNOWN232 in locking bytecode': ['invalid'],
        'OP_UNKNOWN233 in locking bytecode': ['invalid'],
        'OP_UNKNOWN234 in locking bytecode': ['invalid'],
        'OP_UNKNOWN235 in locking bytecode': ['invalid'],
        'OP_UNKNOWN236 in locking bytecode': ['invalid'],
        'OP_UNKNOWN237 in locking bytecode': ['invalid'],
        'OP_UNKNOWN238 in locking bytecode': ['invalid'],
        'OP_UNKNOWN239 in locking bytecode': ['invalid'],
        'OP_UNKNOWN240 in locking bytecode': ['invalid'],
        'OP_UNKNOWN241 in locking bytecode': ['invalid'],
        'OP_UNKNOWN242 in locking bytecode': ['invalid'],
        'OP_UNKNOWN243 in locking bytecode': ['invalid'],
        'OP_UNKNOWN244 in locking bytecode': ['invalid'],
        'OP_UNKNOWN245 in locking bytecode': ['invalid'],
        'OP_UNKNOWN246 in locking bytecode': ['invalid'],
        'OP_UNKNOWN247 in locking bytecode': ['invalid'],
        'OP_UNKNOWN248 in locking bytecode': ['invalid'],
        'OP_UNKNOWN249 in locking bytecode': ['invalid'],
        'OP_UNKNOWN250 in locking bytecode': ['invalid'],
        'OP_UNKNOWN251 in locking bytecode': ['invalid'],
        'OP_UNKNOWN252 in locking bytecode': ['invalid'],
        'OP_UNKNOWN253 in locking bytecode': ['invalid'],
        'OP_UNKNOWN254 in locking bytecode': ['invalid'],
        'OP_UNKNOWN255 in locking bytecode': ['invalid'],
      }),
      ...setExpectedResults(generateTestCases(['$0', '<1>', '$0 in unlocking bytecode'], [unknownOps]), {
        'OP_UNKNOWN189 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN190 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN191 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN212 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN213 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN214 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN215 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN216 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN217 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN218 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN219 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN220 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN221 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN222 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN223 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN224 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN225 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN226 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN227 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN228 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN229 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN230 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN231 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN232 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN233 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN234 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN235 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN236 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN237 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN238 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN239 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN240 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN241 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN242 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN243 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN244 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN245 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN246 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN247 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN248 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN249 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN250 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN251 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN252 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN253 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN254 in unlocking bytecode': ['invalid'],
        'OP_UNKNOWN255 in unlocking bytecode': ['invalid'],
      }),
      ...setExpectedResults(generateTestCases(['<0>', 'OP_IF $0 OP_ENDIF <1>', 'Unexecuted $0 in locking bytecode'], [unknownOps]), {
        'Unexecuted OP_UNKNOWN189 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN190 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN191 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN212 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN213 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN214 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN215 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN216 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN217 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN218 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN219 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN220 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN221 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN222 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN223 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN224 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN225 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN226 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN227 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN228 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN229 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN230 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN231 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN232 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN233 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN234 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN235 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN236 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN237 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN238 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN239 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN240 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN241 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN242 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN243 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN244 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN245 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN246 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN247 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN248 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN249 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN250 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN251 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN252 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN253 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN254 in locking bytecode': [],
        'Unexecuted OP_UNKNOWN255 in locking bytecode': [],
      }),
      ...setExpectedResults(generateTestCases(['<0> OP_IF $0 OP_ENDIF', '<1>', 'Unexecuted $0 in unlocking bytecode'], [unknownOps]), {
        'Unexecuted OP_UNKNOWN189 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN190 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN191 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN212 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN213 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN214 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN215 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN216 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN217 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN218 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN219 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN220 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN221 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN222 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN223 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN224 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN225 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN226 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN227 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN228 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN229 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN230 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN231 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN232 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN233 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN234 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN235 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN236 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN237 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN238 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN239 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN240 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN241 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN242 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN243 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN244 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN245 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN246 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN247 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN248 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN249 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN250 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN251 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN252 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN253 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN254 in unlocking bytecode': ['invalid'],
        'Unexecuted OP_UNKNOWN255 in unlocking bytecode': ['invalid'],
      }),
    ],
  ],
] as const satisfies VmbTestDefinitionGroup[];
