import type { VmbTestDefinitionGroup } from '../../lib.js';
import { generateTestCases, setExpectedResults } from '../bch-vmb-test-utils.js';

export default [
  [
    'Signature checking',
    [
      ...setExpectedResults(
        generateTestCases(
          ['<$0> <$1.$2_signature.all_outputs>', 'OP_1 <$3> <key1.public_key> OP_2 OP_CHECKMULTISIG', '1-of-2 $2 multisig with $0, $1 ($3)'],
          [
            [
              ['checkBits of zero', '0'],
              ['checkBits of key 1', '0b10'],
              ['checkBits of key 2', '0b1'],
            ],
            [
              ['key 1 signature', 'key1'],
              ['key 2 signature', 'key2'],
            ],
            [
              ['ECDSA', 'ecdsa'],
              ['Schnorr', 'schnorr'],
            ],
            [
              ['second public key: valid compressed key2', 'key2.public_key'],
              ['second public key: short arbitrary data', '0x0000000000'],
              ['second public key: excessive length', '0x040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'],
              ['second public key: valid legacy hybrid format', '0x0679be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8'],
              ['second public key: valid uncompressed key2', '0x04c23083dccdc50247ebc5725c88d6d550cc49c9cb94e4bd4c485a1c6715a5dbfd4e56a5f51b754c2f35f95353ff5fd44855e6b28b39ab794d6b354dc2d3629e53'],
            ],
          ],
        ),
        {
          '1-of-2 ECDSA multisig with checkBits of key 1, key 1 signature (second public key: excessive length)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 1, key 1 signature (second public key: short arbitrary data)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 1, key 1 signature (second public key: valid compressed key2)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 1, key 1 signature (second public key: valid legacy hybrid format)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 1, key 1 signature (second public key: valid uncompressed key2)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 1, key 2 signature (second public key: excessive length)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 1, key 2 signature (second public key: short arbitrary data)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 1, key 2 signature (second public key: valid compressed key2)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 1, key 2 signature (second public key: valid legacy hybrid format)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 1, key 2 signature (second public key: valid uncompressed key2)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 2, key 1 signature (second public key: excessive length)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 2, key 1 signature (second public key: short arbitrary data)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 2, key 1 signature (second public key: valid compressed key2)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 2, key 1 signature (second public key: valid legacy hybrid format)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 2, key 1 signature (second public key: valid uncompressed key2)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 2, key 2 signature (second public key: excessive length)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 2, key 2 signature (second public key: short arbitrary data)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 2, key 2 signature (second public key: valid compressed key2)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 2, key 2 signature (second public key: valid legacy hybrid format)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of key 2, key 2 signature (second public key: valid uncompressed key2)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of zero, key 1 signature (second public key: excessive length)': [],
          '1-of-2 ECDSA multisig with checkBits of zero, key 1 signature (second public key: short arbitrary data)': [],
          '1-of-2 ECDSA multisig with checkBits of zero, key 1 signature (second public key: valid compressed key2)': ['p2s_standard'],
          '1-of-2 ECDSA multisig with checkBits of zero, key 1 signature (second public key: valid legacy hybrid format)': ['p2s_standard'],
          '1-of-2 ECDSA multisig with checkBits of zero, key 1 signature (second public key: valid uncompressed key2)': ['p2s_standard'],
          '1-of-2 ECDSA multisig with checkBits of zero, key 2 signature (second public key: excessive length)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of zero, key 2 signature (second public key: short arbitrary data)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of zero, key 2 signature (second public key: valid compressed key2)': ['p2s_standard'],
          '1-of-2 ECDSA multisig with checkBits of zero, key 2 signature (second public key: valid legacy hybrid format)': ['invalid'],
          '1-of-2 ECDSA multisig with checkBits of zero, key 2 signature (second public key: valid uncompressed key2)': ['p2s_standard'],
          '1-of-2 Schnorr multisig with checkBits of key 1, key 1 signature (second public key: excessive length)': [],
          '1-of-2 Schnorr multisig with checkBits of key 1, key 1 signature (second public key: short arbitrary data)': [],
          '1-of-2 Schnorr multisig with checkBits of key 1, key 1 signature (second public key: valid compressed key2)': ['p2s_standard'],
          '1-of-2 Schnorr multisig with checkBits of key 1, key 1 signature (second public key: valid legacy hybrid format)': ['p2s_standard'],
          '1-of-2 Schnorr multisig with checkBits of key 1, key 1 signature (second public key: valid uncompressed key2)': ['p2s_standard'],
          '1-of-2 Schnorr multisig with checkBits of key 1, key 2 signature (second public key: excessive length)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of key 1, key 2 signature (second public key: short arbitrary data)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of key 1, key 2 signature (second public key: valid compressed key2)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of key 1, key 2 signature (second public key: valid legacy hybrid format)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of key 1, key 2 signature (second public key: valid uncompressed key2)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of key 2, key 1 signature (second public key: excessive length)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of key 2, key 1 signature (second public key: short arbitrary data)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of key 2, key 1 signature (second public key: valid compressed key2)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of key 2, key 1 signature (second public key: valid legacy hybrid format)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of key 2, key 1 signature (second public key: valid uncompressed key2)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of key 2, key 2 signature (second public key: excessive length)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of key 2, key 2 signature (second public key: short arbitrary data)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of key 2, key 2 signature (second public key: valid compressed key2)': ['p2s_standard'],
          '1-of-2 Schnorr multisig with checkBits of key 2, key 2 signature (second public key: valid legacy hybrid format)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of key 2, key 2 signature (second public key: valid uncompressed key2)': ['p2s_standard'],
          '1-of-2 Schnorr multisig with checkBits of zero, key 1 signature (second public key: excessive length)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of zero, key 1 signature (second public key: short arbitrary data)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of zero, key 1 signature (second public key: valid compressed key2)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of zero, key 1 signature (second public key: valid legacy hybrid format)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of zero, key 1 signature (second public key: valid uncompressed key2)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of zero, key 2 signature (second public key: excessive length)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of zero, key 2 signature (second public key: short arbitrary data)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of zero, key 2 signature (second public key: valid compressed key2)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of zero, key 2 signature (second public key: valid legacy hybrid format)': ['invalid'],
          '1-of-2 Schnorr multisig with checkBits of zero, key 2 signature (second public key: valid uncompressed key2)': ['invalid'],
        },
      ),
    ],
  ],
] as const satisfies VmbTestDefinitionGroup['invalid'];
