import type { VmbTestDefinitionGroup } from '../../lib.js';
import { generateTestCases, setExpectedResults } from '../bch-vmb-test-utils.js';

export default [
  [
    'Push operation minimal data validation',
    [
      ...setExpectedResults(
        generateTestCases(
          ['$0 $1', '', 'Unlocking bytecode $0 of $1'],
          [
            [
              ['OP_PUSHBYTES_1', 'OP_PUSHBYTES_1'],
              ['OP_PUSHBYTES_2', 'OP_PUSHBYTES_2'],
              ['OP_PUSHDATA_1 1', 'OP_PUSHDATA_1 0x01'],
              ['OP_PUSHDATA_2 1', 'OP_PUSHDATA_2 0x0100'],
              ['OP_PUSHDATA_4 1', 'OP_PUSHDATA_4 0x01000000'],
            ],
            [
              ['-1', '0x81'],
              ['0x00', '0x00'],
              ['0 (empty)', ''],
              ['1', '1'],
              ['2', '2'],
              ['3', '3'],
              ['4', '4'],
              ['5', '5'],
              ['6', '6'],
              ['7', '7'],
              ['8', '8'],
              ['9', '9'],
              ['10', '10'],
              ['11', '11'],
              ['12', '12'],
              ['13', '13'],
              ['14', '14'],
              ['15', '15'],
              ['16', '16'],
              ['17', '17'],
              ['76', '76'],
              ['127', '127'],
              ['128', '128'],
              ['255', '255'],
              ['0x0000', '0x0000'],
            ],
          ],
        ),
        {
          'Unlocking bytecode OP_PUSHBYTES_1 of -1': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 0 (empty)': ['skip'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 0x00': ['skip'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 0x0000': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 1': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 10': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 11': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 12': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 127': [],
          'Unlocking bytecode OP_PUSHBYTES_1 of 128': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 13': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 14': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 15': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 16': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 17': [],
          'Unlocking bytecode OP_PUSHBYTES_1 of 2': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 255': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 3': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 4': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 5': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 6': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 7': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 76': [],
          'Unlocking bytecode OP_PUSHBYTES_1 of 8': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_1 of 9': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of -1': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 0 (empty)': ['skip'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 0x00': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 0x0000': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 1': ['skip'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 10': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 11': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 12': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 127': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 128': [],
          'Unlocking bytecode OP_PUSHBYTES_2 of 13': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 14': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 15': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 16': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 17': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 2': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 255': [],
          'Unlocking bytecode OP_PUSHBYTES_2 of 3': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 4': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 5': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 6': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 7': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 76': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 8': ['invalid'],
          'Unlocking bytecode OP_PUSHBYTES_2 of 9': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of -1': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 0 (empty)': ['skip'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 0x00': ['skip'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 0x0000': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 1': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 10': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 11': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 12': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 127': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 128': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 13': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 14': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 15': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 16': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 17': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 2': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 255': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 3': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 4': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 5': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 6': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 7': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 76': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 8': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_1 1 of 9': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of -1': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 0 (empty)': ['skip'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 0x00': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 0x0000': ['skip'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 1': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 10': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 11': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 12': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 127': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 128': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 13': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 14': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 15': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 16': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 17': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 2': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 255': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 3': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 4': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 5': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 6': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 7': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 76': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 8': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_2 1 of 9': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of -1': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 0 (empty)': ['skip'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 0x00': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 0x0000': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 1': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 10': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 11': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 12': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 127': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 128': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 13': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 14': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 15': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 16': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 17': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 2': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 255': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 3': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 4': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 5': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 6': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 7': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 76': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 8': ['invalid'],
          'Unlocking bytecode OP_PUSHDATA_4 1 of 9': ['invalid'],
        },
      ),

      ...setExpectedResults(
        generateTestCases(
          ['<0> OP_IF $0 $1 OP_ENDIF <1>', '', 'Unexecuted conditional in unlocking bytecode, $0 of $1'],
          [
            [
              ['OP_PUSHBYTES_1', 'OP_PUSHBYTES_1'],
              ['OP_PUSHBYTES_2', 'OP_PUSHBYTES_2'],
              ['OP_PUSHDATA_1 1', 'OP_PUSHDATA_1 0x01'],
              ['OP_PUSHDATA_2 1', 'OP_PUSHDATA_2 0x0100'],
              ['OP_PUSHDATA_4 1', 'OP_PUSHDATA_4 0x01000000'],
            ],
            [
              ['-1', '0x81'],
              ['0x00', '0x00'],
              ['0 (empty)', ''],
              ['1', '1'],
              ['2', '2'],
              ['3', '3'],
              ['4', '4'],
              ['5', '5'],
              ['6', '6'],
              ['7', '7'],
              ['8', '8'],
              ['9', '9'],
              ['10', '10'],
              ['11', '11'],
              ['12', '12'],
              ['13', '13'],
              ['14', '14'],
              ['15', '15'],
              ['16', '16'],
              ['17', '17'],
              ['76', '76'],
              ['127', '127'],
              ['128', '128'],
              ['255', '255'],
              ['0x0000', '0x0000'],
            ],
          ],
        ),
        {
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of -1': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 0 (empty)': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 0x00': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 0x0000': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 1': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 10': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 11': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 12': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 127': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 128': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 13': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 14': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 15': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 16': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 17': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 2': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 255': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 3': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 4': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 5': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 6': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 7': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 76': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 8': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_1 of 9': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of -1': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 0 (empty)': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 0x00': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 0x0000': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 1': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 10': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 11': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 12': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 127': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 128': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 13': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 14': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 15': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 16': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 17': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 2': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 255': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 3': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 4': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 5': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 6': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 7': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 76': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 8': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHBYTES_2 of 9': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of -1': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 0 (empty)': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 0x00': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 0x0000': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 1': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 10': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 11': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 12': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 127': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 128': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 13': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 14': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 15': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 16': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 17': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 2': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 255': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 3': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 4': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 5': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 6': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 7': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 76': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 8': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_1 1 of 9': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of -1': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 0 (empty)': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 0x00': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 0x0000': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 1': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 10': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 11': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 12': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 127': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 128': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 13': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 14': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 15': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 16': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 17': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 2': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 255': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 3': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 4': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 5': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 6': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 7': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 76': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 8': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_2 1 of 9': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of -1': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 0 (empty)': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 0x00': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 0x0000': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 1': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 10': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 11': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 12': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 127': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 128': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 13': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 14': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 15': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 16': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 17': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 2': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 255': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 3': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 4': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 5': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 6': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 7': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 76': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 8': ['invalid'],
          'Unexecuted conditional in unlocking bytecode, OP_PUSHDATA_4 1 of 9': ['invalid'],
        },
      ),

      ...setExpectedResults(
        generateTestCases(
          ['', '$0 $1', 'Locking bytecode $0 of $1'],
          [
            [
              ['OP_PUSHBYTES_1', 'OP_PUSHBYTES_1'],
              ['OP_PUSHBYTES_2', 'OP_PUSHBYTES_2'],
              ['OP_PUSHDATA_1 1', 'OP_PUSHDATA_1 0x01'],
              ['OP_PUSHDATA_2 1', 'OP_PUSHDATA_2 0x0100'],
              ['OP_PUSHDATA_4 1', 'OP_PUSHDATA_4 0x01000000'],
            ],
            [
              ['-1', '0x81'],
              ['0x00', '0x00'],
              ['0 (empty)', ''],
              ['1', '1'],
              ['2', '2'],
              ['3', '3'],
              ['4', '4'],
              ['5', '5'],
              ['6', '6'],
              ['7', '7'],
              ['8', '8'],
              ['9', '9'],
              ['10', '10'],
              ['11', '11'],
              ['12', '12'],
              ['13', '13'],
              ['14', '14'],
              ['15', '15'],
              ['16', '16'],
              ['17', '17'],
              ['76', '76'],
              ['127', '127'],
              ['128', '128'],
              ['255', '255'],
              ['0x0000', '0x0000'],
            ],
          ],
        ),
        {
          'Locking bytecode OP_PUSHBYTES_1 of -1': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 0 (empty)': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 0x00': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 0x0000': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 1': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 10': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 11': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 12': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 127': [],
          'Locking bytecode OP_PUSHBYTES_1 of 128': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 13': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 14': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 15': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 16': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 17': [],
          'Locking bytecode OP_PUSHBYTES_1 of 2': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 255': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 3': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 4': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 5': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 6': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 7': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 76': [],
          'Locking bytecode OP_PUSHBYTES_1 of 8': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_1 of 9': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of -1': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 0 (empty)': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 0x00': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 0x0000': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 1': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 10': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 11': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 12': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 127': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 128': [],
          'Locking bytecode OP_PUSHBYTES_2 of 13': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 14': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 15': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 16': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 17': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 2': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 255': [],
          'Locking bytecode OP_PUSHBYTES_2 of 3': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 4': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 5': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 6': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 7': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 76': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 8': ['invalid'],
          'Locking bytecode OP_PUSHBYTES_2 of 9': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of -1': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 0 (empty)': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 0x00': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 0x0000': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 1': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 10': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 11': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 12': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 127': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 128': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 13': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 14': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 15': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 16': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 17': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 2': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 255': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 3': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 4': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 5': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 6': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 7': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 76': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 8': ['invalid'],
          'Locking bytecode OP_PUSHDATA_1 1 of 9': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of -1': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 0 (empty)': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 0x00': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 0x0000': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 1': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 10': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 11': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 12': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 127': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 128': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 13': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 14': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 15': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 16': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 17': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 2': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 255': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 3': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 4': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 5': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 6': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 7': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 76': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 8': ['invalid'],
          'Locking bytecode OP_PUSHDATA_2 1 of 9': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of -1': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 0 (empty)': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 0x00': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 0x0000': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 1': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 10': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 11': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 12': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 127': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 128': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 13': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 14': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 15': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 16': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 17': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 2': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 255': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 3': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 4': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 5': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 6': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 7': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 76': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 8': ['invalid'],
          'Locking bytecode OP_PUSHDATA_4 1 of 9': ['invalid'],
        },
      ),

      ...setExpectedResults(
        generateTestCases(
          ['', '<0> OP_IF $0 $1 OP_ENDIF <1>', 'Unexecuted conditional in locking bytecode, $0 of $1'],
          [
            [
              ['OP_PUSHBYTES_1', 'OP_PUSHBYTES_1'],
              ['OP_PUSHBYTES_2', 'OP_PUSHBYTES_2'],
              ['OP_PUSHDATA_1 1', 'OP_PUSHDATA_1 0x01'],
              ['OP_PUSHDATA_2 1', 'OP_PUSHDATA_2 0x0100'],
              ['OP_PUSHDATA_4 1', 'OP_PUSHDATA_4 0x01000000'],
            ],
            [
              ['-1', '0x81'],
              ['0x00', '0x00'],
              ['0 (empty)', ''],
              ['1', '1'],
              ['2', '2'],
              ['3', '3'],
              ['4', '4'],
              ['5', '5'],
              ['6', '6'],
              ['7', '7'],
              ['8', '8'],
              ['9', '9'],
              ['10', '10'],
              ['11', '11'],
              ['12', '12'],
              ['13', '13'],
              ['14', '14'],
              ['15', '15'],
              ['16', '16'],
              ['17', '17'],
              ['76', '76'],
              ['127', '127'],
              ['128', '128'],
              ['255', '255'],
              ['0x0000', '0x0000'],
            ],
          ],
        ),
        {
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of -1': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 0 (empty)': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 0x00': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 0x0000': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 1': ['skip'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 10': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 11': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 12': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 127': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 128': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 13': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 14': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 15': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 16': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 17': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 2': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 255': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 3': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 4': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 5': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 6': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 7': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 76': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 8': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_1 of 9': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of -1': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 0 (empty)': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 0x00': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 0x0000': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 1': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 10': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 11': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 12': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 127': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 128': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 13': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 14': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 15': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 16': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 17': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 2': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 255': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 3': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 4': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 5': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 6': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 7': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 76': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 8': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHBYTES_2 of 9': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of -1': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 0 (empty)': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 0x00': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 0x0000': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 1': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 10': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 11': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 12': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 127': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 128': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 13': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 14': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 15': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 16': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 17': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 2': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 255': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 3': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 4': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 5': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 6': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 7': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 76': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 8': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_1 1 of 9': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of -1': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 0 (empty)': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 0x00': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 0x0000': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 1': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 10': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 11': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 12': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 127': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 128': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 13': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 14': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 15': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 16': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 17': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 2': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 255': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 3': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 4': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 5': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 6': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 7': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 76': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 8': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_2 1 of 9': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of -1': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 0 (empty)': ['invalid'],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 0x00': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 0x0000': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 1': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 10': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 11': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 12': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 127': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 128': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 13': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 14': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 15': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 16': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 17': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 2': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 255': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 3': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 4': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 5': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 6': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 7': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 76': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 8': [],
          'Unexecuted conditional in locking bytecode, OP_PUSHDATA_4 1 of 9': [],
        },
      ),
    ],
  ],
] as const satisfies VmbTestDefinitionGroup[];
