import type { PossibleTestValue, VmbTestDefinitionGroup } from '../../lib.js';
import { generateTestCases, setExpectedResults } from '../bch-vmb-test-utils.js';

const signingSerializationAlgorithms: PossibleTestValue[] = [
  ['all_outputs', 'all_outputs'],
  ['all_outputs_all_utxos', 'all_outputs_all_utxos'],
  ['all_outputs_single_input', 'all_outputs_single_input'],
  ['corresponding_output', 'corresponding_output'],
  ['corresponding_output_all_utxos', 'corresponding_output_all_utxos'],
  ['corresponding_output_single_input', 'corresponding_output_single_input'],
  ['no_outputs', 'no_outputs'],
  ['no_outputs_all_utxos', 'no_outputs_all_utxos'],
  ['no_outputs_single_input', 'no_outputs_single_input'],
];

export default [
  [
    'Signature checking',
    [
      ...setExpectedResults(generateTestCases(['<0> <key1.ecdsa_signature.$0> <key2.ecdsa_signature.$1>', '<2> <key1.public_key> <key2.public_key> <key3.public_key> OP_3 OP_CHECKMULTISIG', '2-of-3 ECDSA multisig ($0, $1)'], [signingSerializationAlgorithms, signingSerializationAlgorithms]), {
        '2-of-3 ECDSA multisig (all_outputs, all_outputs)': ['skip'],
        '2-of-3 ECDSA multisig (all_outputs, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs, no_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_all_utxos, all_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_all_utxos, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_all_utxos, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_all_utxos, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_all_utxos, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_all_utxos, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_all_utxos, no_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_all_utxos, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_all_utxos, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_single_input, all_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_single_input, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_single_input, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_single_input, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_single_input, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_single_input, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_single_input, no_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_single_input, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (all_outputs_single_input, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output, all_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output, no_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_all_utxos, all_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_all_utxos, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_all_utxos, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_all_utxos, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_all_utxos, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_all_utxos, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_all_utxos, no_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_all_utxos, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_all_utxos, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_single_input, all_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_single_input, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_single_input, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_single_input, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_single_input, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_single_input, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_single_input, no_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_single_input, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (corresponding_output_single_input, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs, all_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs, no_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_all_utxos, all_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_all_utxos, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_all_utxos, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_all_utxos, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_all_utxos, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_all_utxos, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_all_utxos, no_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_all_utxos, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_all_utxos, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_single_input, all_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_single_input, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_single_input, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_single_input, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_single_input, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_single_input, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_single_input, no_outputs)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_single_input, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 ECDSA multisig (no_outputs_single_input, no_outputs_single_input)': ['nop2sh_standard'],
      }),
      ...setExpectedResults(generateTestCases(['<0b011> <key1.schnorr_signature.$0> <key2.schnorr_signature.$1>', '<2> <key1.public_key> <key2.public_key> <key3.public_key> OP_3 OP_CHECKMULTISIG', '2-of-3 Schnorr multisig ($0, $1)'], [signingSerializationAlgorithms, signingSerializationAlgorithms]), {
        '2-of-3 Schnorr multisig (all_outputs, all_outputs)': ['skip'],
        '2-of-3 Schnorr multisig (all_outputs, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs, no_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_all_utxos, all_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_all_utxos, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_all_utxos, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_all_utxos, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_all_utxos, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_all_utxos, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_all_utxos, no_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_all_utxos, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_all_utxos, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_single_input, all_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_single_input, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_single_input, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_single_input, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_single_input, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_single_input, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_single_input, no_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_single_input, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (all_outputs_single_input, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output, all_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output, no_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_all_utxos, all_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_all_utxos, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_all_utxos, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_all_utxos, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_all_utxos, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_all_utxos, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_all_utxos, no_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_all_utxos, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_all_utxos, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_single_input, all_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_single_input, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_single_input, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_single_input, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_single_input, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_single_input, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_single_input, no_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_single_input, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (corresponding_output_single_input, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs, all_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs, no_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_all_utxos, all_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_all_utxos, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_all_utxos, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_all_utxos, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_all_utxos, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_all_utxos, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_all_utxos, no_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_all_utxos, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_all_utxos, no_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_single_input, all_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_single_input, all_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_single_input, all_outputs_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_single_input, corresponding_output)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_single_input, corresponding_output_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_single_input, corresponding_output_single_input)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_single_input, no_outputs)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_single_input, no_outputs_all_utxos)': ['nop2sh_standard'],
        '2-of-3 Schnorr multisig (no_outputs_single_input, no_outputs_single_input)': ['nop2sh_standard'],
      }),
    ],
  ],
] as const satisfies VmbTestDefinitionGroup[];
