import { range } from '../../format/format.js';
import type { PossibleTestValue, VmbTestDefinitionGroup } from '../../lib.js';
import { generateTestCases, setExpectedResults } from '../bch-vmb-test-utils.js';

const dataSigOps: PossibleTestValue[] = [
  ['OP_CHECKDATASIG', 'OP_CHECKDATASIG'],
  ['OP_CHECKDATASIGVERIFY <1>', 'OP_CHECKDATASIGVERIFY <1>'],
];

const byteLengths = [...range(56, 1), 64, 119, 120, 183, 184, 247, 248, 488, 503, 504, 520, 521, 1015, 1016];
const byteLengthTestValues: PossibleTestValue[] = byteLengths.map((i) => [`${i}`, `${i}`]);

export default [
  [
    'Data signatures',
    [
      ...setExpectedResults(
        generateTestCases(['<key1.ecdsa_data_signature.additional_script$0>', `<0> <$0> OP_NUM2BIN <key1.public_key> $1`, '$1 for $0 byte message'], [byteLengthTestValues, dataSigOps], {
          additionalScripts: {
            ...Object.fromEntries(byteLengths.map((i) => [`additional_script${i}`, { script: `$(<0> <${i}> OP_NUM2BIN)` }])),
          },
        }),
        {
          'OP_CHECKDATASIG for 1 byte message': [],
          'OP_CHECKDATASIG for 10 byte message': [],
          'OP_CHECKDATASIG for 1015 byte message': ['2023_invalid'],
          'OP_CHECKDATASIG for 1016 byte message': ['2023_invalid'],
          'OP_CHECKDATASIG for 11 byte message': [],
          'OP_CHECKDATASIG for 119 byte message': [],
          'OP_CHECKDATASIG for 12 byte message': [],
          'OP_CHECKDATASIG for 120 byte message': [],
          'OP_CHECKDATASIG for 13 byte message': [],
          'OP_CHECKDATASIG for 14 byte message': [],
          'OP_CHECKDATASIG for 15 byte message': [],
          'OP_CHECKDATASIG for 16 byte message': [],
          'OP_CHECKDATASIG for 17 byte message': [],
          'OP_CHECKDATASIG for 18 byte message': [],
          'OP_CHECKDATASIG for 183 byte message': [],
          'OP_CHECKDATASIG for 184 byte message': [],
          'OP_CHECKDATASIG for 19 byte message': [],
          'OP_CHECKDATASIG for 2 byte message': [],
          'OP_CHECKDATASIG for 20 byte message': [],
          'OP_CHECKDATASIG for 21 byte message': [],
          'OP_CHECKDATASIG for 22 byte message': [],
          'OP_CHECKDATASIG for 23 byte message': [],
          'OP_CHECKDATASIG for 24 byte message': [],
          'OP_CHECKDATASIG for 247 byte message': [],
          'OP_CHECKDATASIG for 248 byte message': [],
          'OP_CHECKDATASIG for 25 byte message': [],
          'OP_CHECKDATASIG for 26 byte message': [],
          'OP_CHECKDATASIG for 27 byte message': [],
          'OP_CHECKDATASIG for 28 byte message': [],
          'OP_CHECKDATASIG for 29 byte message': [],
          'OP_CHECKDATASIG for 3 byte message': [],
          'OP_CHECKDATASIG for 30 byte message': [],
          'OP_CHECKDATASIG for 31 byte message': [],
          'OP_CHECKDATASIG for 32 byte message': [],
          'OP_CHECKDATASIG for 33 byte message': [],
          'OP_CHECKDATASIG for 34 byte message': [],
          'OP_CHECKDATASIG for 35 byte message': [],
          'OP_CHECKDATASIG for 36 byte message': [],
          'OP_CHECKDATASIG for 37 byte message': [],
          'OP_CHECKDATASIG for 38 byte message': [],
          'OP_CHECKDATASIG for 39 byte message': [],
          'OP_CHECKDATASIG for 4 byte message': [],
          'OP_CHECKDATASIG for 40 byte message': [],
          'OP_CHECKDATASIG for 41 byte message': [],
          'OP_CHECKDATASIG for 42 byte message': [],
          'OP_CHECKDATASIG for 43 byte message': [],
          'OP_CHECKDATASIG for 44 byte message': [],
          'OP_CHECKDATASIG for 45 byte message': [],
          'OP_CHECKDATASIG for 46 byte message': [],
          'OP_CHECKDATASIG for 47 byte message': [],
          'OP_CHECKDATASIG for 48 byte message': [],
          'OP_CHECKDATASIG for 488 byte message': [],
          'OP_CHECKDATASIG for 49 byte message': [],
          'OP_CHECKDATASIG for 5 byte message': [],
          'OP_CHECKDATASIG for 50 byte message': [],
          'OP_CHECKDATASIG for 503 byte message': [],
          'OP_CHECKDATASIG for 504 byte message': [],
          'OP_CHECKDATASIG for 51 byte message': [],
          'OP_CHECKDATASIG for 52 byte message': [],
          'OP_CHECKDATASIG for 520 byte message': [],
          'OP_CHECKDATASIG for 521 byte message': ['2023_invalid'],
          'OP_CHECKDATASIG for 53 byte message': [],
          'OP_CHECKDATASIG for 54 byte message': [],
          'OP_CHECKDATASIG for 55 byte message': [],
          'OP_CHECKDATASIG for 56 byte message': [],
          'OP_CHECKDATASIG for 6 byte message': [],
          'OP_CHECKDATASIG for 64 byte message': [],
          'OP_CHECKDATASIG for 7 byte message': [],
          'OP_CHECKDATASIG for 8 byte message': [],
          'OP_CHECKDATASIG for 9 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 1 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 10 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 1015 byte message': ['2023_invalid'],
          'OP_CHECKDATASIGVERIFY <1> for 1016 byte message': ['2023_invalid'],
          'OP_CHECKDATASIGVERIFY <1> for 11 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 119 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 12 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 120 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 13 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 14 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 15 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 16 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 17 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 18 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 183 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 184 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 19 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 2 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 20 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 21 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 22 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 23 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 24 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 247 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 248 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 25 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 26 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 27 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 28 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 29 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 3 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 30 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 31 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 32 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 33 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 34 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 35 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 36 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 37 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 38 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 39 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 4 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 40 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 41 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 42 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 43 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 44 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 45 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 46 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 47 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 48 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 488 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 49 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 5 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 50 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 503 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 504 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 51 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 52 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 520 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 521 byte message': ['2023_invalid'],
          'OP_CHECKDATASIGVERIFY <1> for 53 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 54 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 55 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 56 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 6 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 64 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 7 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 8 byte message': [],
          'OP_CHECKDATASIGVERIFY <1> for 9 byte message': [],
        },
      ),
    ],
  ],
] as const satisfies VmbTestDefinitionGroup[];
