cacheFolder: './.yarn/cache'
enableGlobalCache: false
enableScripts: false
nodeLinker: pnp
yarnPath: .yarn/releases/yarn-4.0.2.cjs
supportedArchitectures:
  cpu:
    - 'arm64'
    - 'x64'
  libc:
    - 'glibc'
    - 'musl'
  os:
    - 'darwin'
    - 'linux'
    - 'win32'
