cacheFolder: ./.yarn/cache

enableGlobalCache: false

enableScripts: false

nodeLinker: pnp

supportedArchitectures:
  cpu:
    - arm64
    - x64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.5.0.cjs
